# DP Global configuration
# See config.default.yml for default values

collector:
  export:
    google_spread_sheet:
      source_name:  "DAL_crashtest"
      target_name:  "DAL_crashtest"
      #target_name: "Fading Suns"
      credentials:  "collector/creds.json"
      tab:          "Characters"
      tab_abstract: "Abstract"
    pc_summary:
      source_name:  "DAL - Player Characters"
      target_name:  "DAL - Player Characters"
      tab:          "Characters"
      tab_abstract: "Abstract"
      credentials:  "collector/creds.json"