# Generated by Django 2.2 on 2021-03-04 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256, unique=True)),
                ('chapter', models.CharField(blank=True, default='0', max_length=64)),
                ('date', models.CharField(blank=True, default='', max_length=128)),
                ('place', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=2560)),
                ('gamemaster', models.CharField(blank=True, default='zaffarelli@gmail.com', max_length=128)),
                ('visible', models.BooleanField(default=True)),
                ('to_PDF', models.BooleanField(default=True)),
                ('full_id', models.CharField(blank=True, default='', max_length=64)),
                ('resolution', models.TextField(blank=True, default='', max_length=2560)),
            ],
            options={
                'ordering': ['chapter', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256, unique=True)),
                ('chapter', models.CharField(blank=True, default='0', max_length=64)),
                ('date', models.CharField(blank=True, default='', max_length=128)),
                ('place', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=2560)),
                ('gamemaster', models.CharField(blank=True, default='zaffarelli@gmail.com', max_length=128)),
                ('visible', models.BooleanField(default=True)),
                ('to_PDF', models.BooleanField(default=True)),
                ('full_id', models.CharField(blank=True, default='', max_length=64)),
                ('resolution', models.TextField(blank=True, default='', max_length=2560)),
            ],
            options={
                'ordering': ['epic', 'chapter', 'date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256, unique=True)),
                ('chapter', models.CharField(blank=True, default='0', max_length=64)),
                ('date', models.CharField(blank=True, default='', max_length=128)),
                ('place', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=2560)),
                ('gamemaster', models.CharField(blank=True, default='zaffarelli@gmail.com', max_length=128)),
                ('visible', models.BooleanField(default=True)),
                ('to_PDF', models.BooleanField(default=True)),
                ('full_id', models.CharField(blank=True, default='', max_length=64)),
                ('era', models.IntegerField(blank=True, default=5017)),
                ('shortcut', models.CharField(blank=True, default='xx', max_length=32)),
                ('image', models.CharField(blank=True, default='', max_length=64)),
                ('system', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'ordering': ['era', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuizzQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512)),
                ('num', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(default='', max_length=64)),
                ('text', models.CharField(blank=True, max_length=128)),
                ('size', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='QuizzAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('num', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(default='', max_length=512)),
                ('challenge', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=3)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarist.QuizzQuestion')),
            ],
            options={
                'ordering': ['question', 'num'],
            },
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveIntegerField(default=1)),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.Act')),
                ('ally', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ally', to='scenarist.QuizzAnswer')),
                ('climax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climax', to='scenarist.QuizzAnswer')),
                ('complication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complication', to='scenarist.QuizzAnswer')),
                ('drama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.Drama')),
                ('framingevent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framing_event', to='scenarist.QuizzAnswer')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal', to='scenarist.QuizzAnswer')),
                ('introduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduction', to='scenarist.QuizzAnswer')),
                ('patron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patron', to='scenarist.QuizzAnswer')),
                ('sidequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_quest', to='scenarist.QuizzAnswer')),
                ('twist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twist', to='scenarist.QuizzAnswer')),
                ('villain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villain', to='scenarist.QuizzAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256, unique=True)),
                ('chapter', models.CharField(blank=True, default='0', max_length=64)),
                ('date', models.CharField(blank=True, default='', max_length=128)),
                ('place', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=2560)),
                ('gamemaster', models.CharField(blank=True, default='zaffarelli@gmail.com', max_length=128)),
                ('visible', models.BooleanField(default=True)),
                ('to_PDF', models.BooleanField(default=True)),
                ('full_id', models.CharField(blank=True, default='', max_length=64)),
                ('resolution', models.TextField(blank=True, default='', max_length=2560)),
                ('challenge', models.PositiveIntegerField(default=1)),
                ('anchor', models.CharField(blank=True, default='', max_length=256)),
                ('act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.Act')),
            ],
            options={
                'ordering': ['chapter', 'title'],
            },
        ),
        migrations.AddField(
            model_name='drama',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.Epic'),
        ),
        migrations.AddField(
            model_name='act',
            name='drama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.Drama'),
        ),
    ]
