# Generated by Django 2.1 on 2018-12-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128, unique=True)),
                ('date', models.CharField(blank=True, default='', max_length=128)),
                ('population_count', models.IntegerField(blank=True, default=0)),
                ('antagonists', models.TextField(blank=True, default='', max_length=640)),
                ('protagonists', models.TextField(blank=True, default='', max_length=640)),
                ('description', models.TextField(blank=True, default='', max_length=640)),
                ('gamemaster', models.CharField(blank=True, default='zaffarelli@gmail.com', max_length=128)),
            ],
            options={
                'ordering': ['date', 'title'],
            },
        ),
    ]
