# Generated by Django 2.2 on 2021-11-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='rewards',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='drama',
            name='rewards',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='epic',
            name='rewards',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='event',
            name='rewards',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='act',
            name='description',
            field=models.TextField(blank=True, default='', max_length=6000),
        ),
        migrations.AlterField(
            model_name='drama',
            name='description',
            field=models.TextField(blank=True, default='', max_length=6000),
        ),
        migrations.AlterField(
            model_name='epic',
            name='description',
            field=models.TextField(blank=True, default='', max_length=6000),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', max_length=6000),
        ),
    ]
