# Generated by Django 2.2.7 on 2020-03-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drama',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epic',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
