# Generated by Django 4.1.4 on 2023-04-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='story_cards',
        ),
    ]
