# Generated by Django 4.1.4 on 2023-04-12 22:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
    ]
