# Generated by Django 4.1.4 on 2023-04-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0002_card_dramatis_personae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='sublevels',
        ),
    ]
