# Generated by Django 4.1.4 on 2023-04-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0002_alter_card_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table=None,
        ),
    ]
