# Generated by Django 2.2.7 on 2020-03-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0002_auto_20200320_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='population_count',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='population_count',
        ),
        migrations.RemoveField(
            model_name='epic',
            name='population_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='population_count',
        ),
    ]
