# Generated by Django 2.1 on 2018-12-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0002_auto_20181210_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='drama',
            new_name='act',
        ),
    ]
