# Generated by Django 2.1 on 2018-12-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0003_auto_20181210_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='players',
            field=models.TextField(blank=True, default='', max_length=640),
        ),
    ]
