# Generated by Django 2.2 on 2022-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0003_auto_20211228_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='drama',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='epic',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background')], default='UN', max_length=2),
        ),
    ]
