# Generated by Django 2.2 on 2020-10-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0004_quizzanswer_quizzquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizzanswer',
            options={'ordering': ['question', 'num']},
        ),
        migrations.AlterModelOptions(
            name='quizzquestion',
            options={'ordering': ['num']},
        ),
    ]
