# Generated by Django 4.1.4 on 2023-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0004_card_dramatis_personae'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_type', 'name']},
        ),
        migrations.AddField(
            model_name='card',
            name='era',
            field=models.IntegerField(blank=True, default=4997),
        ),
    ]
