# Generated by Django 2.2 on 2020-10-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0005_auto_20201024_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizzanswer',
            options={'ordering': ['question', 'name']},
        ),
        migrations.AddField(
            model_name='quizzanswer',
            name='challenge',
            field=models.IntegerField(default=1),
        ),
    ]
