# Generated by Django 2.1 on 2018-12-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0005_auto_20181212_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='narrative',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='drama',
            old_name='narrative',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='narrative',
            new_name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='challenge',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
