# Generated by Django 4.1.4 on 2023-04-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0005_alter_card_options_card_era'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='place',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
