# Generated by Django 2.1 on 2018-12-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0006_auto_20181212_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(blank=True, default='1544984519.845719', max_length=128, unique=True),
        ),
    ]
