# Generated by Django 2.1 on 2018-12-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0007_auto_20181216_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(blank=True, default='1544984669.9239767', max_length=128, unique=True),
        ),
    ]
