# Generated by Django 2.2 on 2020-10-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0007_auto_20201024_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzquestion',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
