# Generated by Django 2.1 on 2018-12-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0008_auto_20181216_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(blank=True, default='1544985283.4593084', max_length=128, unique=True),
        ),
    ]
