# Generated by Django 2.2 on 2020-10-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0008_quizzquestion_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzanswer',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
