# Generated by Django 2.2 on 2022-08-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0008_auto_20220819_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='act',
        ),
        migrations.AddField(
            model_name='act',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventure',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backlog',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drama',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epic',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene',
            name='adventure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.Adventure'),
        ),
        migrations.AddField(
            model_name='scene',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
