# Generated by Django 2.2 on 2020-10-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0009_quizzanswer_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzquestion',
            name='name',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
