# Generated by Django 2.2 on 2022-08-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0009_auto_20220819_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='act',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='anchor',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='challenge',
        ),
        migrations.AddField(
            model_name='adventure',
            name='resolution',
            field=models.TextField(blank=True, default='', max_length=2560),
        ),
        migrations.AddField(
            model_name='backlog',
            name='resolution',
            field=models.TextField(blank=True, default='', max_length=2560),
        ),
        migrations.AddField(
            model_name='epic',
            name='resolution',
            field=models.TextField(blank=True, default='', max_length=2560),
        ),
        migrations.AddField(
            model_name='scheme',
            name='adventure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.Adventure'),
        ),
    ]
