# Generated by Django 2.2 on 2020-10-29 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0010_auto_20201029_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='climax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climax', to='scenarist.QuizzAnswer'),
        ),
    ]
