# Generated by Django 2.2 on 2022-08-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0011_auto_20220819_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='backlogs',
            field=models.ManyToManyField(to='scenarist.Backlog'),
        ),
    ]
