# Generated by Django 2.2 on 2020-10-29 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0011_quizz_climax'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='complication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complication', to='scenarist.QuizzAnswer'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='framing_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framing_event', to='scenarist.QuizzAnswer'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='introduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduction', to='scenarist.QuizzAnswer'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='side_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_story', to='scenarist.QuizzAnswer'),
        ),
    ]
