# Generated by Django 2.2 on 2022-08-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0012_adventure_backlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
