# Generated by Django 2.1 on 2018-12-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0012_auto_20181216_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(blank=True, default='1544991825.5110555', max_length=128, unique=True),
        ),
    ]
