# Generated by Django 2.2 on 2020-10-29 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0012_auto_20201029_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='associated_story',
        ),
        migrations.AddField(
            model_name='quizz',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.Act'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='drama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.Drama'),
        ),
    ]
