# Generated by Django 2.1 on 2018-12-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0013_auto_20181216_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(blank=True, default='1544991866.6102064', max_length=128, unique=True),
        ),
    ]
