# Generated by Django 2.2 on 2022-08-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0013_scene_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['chapter', 'name']},
        ),
        migrations.AlterModelOptions(
            name='adventure',
            options={'ordering': ['chapter', 'name']},
        ),
        migrations.AlterModelOptions(
            name='backlog',
            options={'ordering': ['chapter', 'name']},
        ),
        migrations.AlterModelOptions(
            name='drama',
            options={'ordering': ['epic', 'chapter', 'date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='epic',
            options={'ordering': ['era', 'name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['chapter', 'name']},
        ),
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['chapter', 'name']},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'ordering': ['chapter', 'name']},
        ),
        migrations.RenameField(
            model_name='act',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='adventure',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='backlog',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='drama',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='epic',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='scene',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='title',
            new_name='name',
        ),
    ]
