# Generated by Django 2.2 on 2020-10-29 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0013_auto_20201029_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizz',
            old_name='drama',
            new_name='associated_story',
        ),
    ]
