# Generated by Django 2.2 on 2022-08-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0014_auto_20220822_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='backlogs',
            field=models.ManyToManyField(to='scenarist.Backlog'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='backlogs',
            field=models.ManyToManyField(to='scenarist.Backlog'),
        ),
    ]
