# Generated by Django 2.2 on 2020-10-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0014_auto_20201029_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizz',
            old_name='associated_story',
            new_name='drama',
        ),
    ]
