# Generated by Django 2.2 on 2020-10-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0015_auto_20201029_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzanswer',
            name='weight',
            field=models.IntegerField(default=3),
        ),
    ]
