# Generated by Django 2.2 on 2022-08-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0015_auto_20220822_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='backlogs',
            field=models.ManyToManyField(blank=True, to='scenarist.Backlog'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='backlogs',
            field=models.ManyToManyField(blank=True, to='scenarist.Backlog'),
        ),
    ]
