# Generated by Django 2.1 on 2018-12-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0016_auto_20181216_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(blank=True, default='1544992097.0106142', max_length=128, unique=True),
        ),
    ]
