# Generated by Django 2.2 on 2022-08-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0016_auto_20220822_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='backlogs',
            field=models.ManyToManyField(blank=True, to='scenarist.Backlog'),
        ),
    ]
