# Generated by Django 2.1 on 2018-12-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0017_auto_20181216_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(blank=True, default='1544992225.1034951', max_length=128, unique=True),
        ),
    ]
