# Generated by Django 4.1.4 on 2023-01-01 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0018_backlog_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, unique=True)),
                ('chapter', models.PositiveIntegerField(blank=True, default=0)),
                ('date_offset', models.IntegerField(blank=True, default=0)),
                ('dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('place', models.CharField(blank=True, default='', max_length=128)),
                ('gamemaster', models.CharField(blank=True, default='zaffarelli@gmail.com', max_length=128)),
                ('visible', models.BooleanField(default=True)),
                ('battle_scene', models.BooleanField(default=False)),
                ('chase_scene', models.BooleanField(default=False)),
                ('action_scene', models.BooleanField(default=False)),
                ('technical_scene', models.BooleanField(default=False)),
                ('spiritual_scene', models.BooleanField(default=False)),
                ('political_scene', models.BooleanField(default=False)),
                ('downtime_scene', models.BooleanField(default=False)),
                ('to_PDF', models.BooleanField(default=True)),
                ('temporary', models.BooleanField(default=True)),
                ('full_id', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='', max_length=6000)),
                ('resolution', models.TextField(blank=True, default='', max_length=2560)),
                ('rewards', models.TextField(blank=True, default='', max_length=1024)),
                ('card_type', models.CharField(blank=True, choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['full_id', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='drama',
            options={'ordering': ['epic', 'chapter', 'date_offset', 'name']},
        ),
        migrations.RemoveField(
            model_name='act',
            name='date',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='date',
        ),
        migrations.RemoveField(
            model_name='backlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='date',
        ),
        migrations.RemoveField(
            model_name='epic',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='date',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='date',
        ),
        migrations.AddField(
            model_name='act',
            name='date_offset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='act',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='date_offset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='adventure',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='backlog',
            name='date_offset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='backlog',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='date_offset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='drama',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='date_offset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='epic',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_offset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='date_offset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='date_offset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scheme',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='card_type',
            field=models.CharField(blank=True, choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='act',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='card_type',
            field=models.CharField(blank=True, choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='card_type',
            field=models.CharField(blank=True, choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='drama',
            name='card_type',
            field=models.CharField(blank=True, choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='drama',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='epic',
            name='card_type',
            field=models.CharField(blank=True, choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='epic',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='card_type',
            field=models.CharField(blank=True, choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scene',
            name='card_type',
            field=models.CharField(blank=True, choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='scene',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='card_type',
            field=models.CharField(blank=True, choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='CardLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('UN', 'Undefined'), ('PO', 'Parent of'), ('EX', 'Explains'), ('CO', 'consequence of'), ('CH', 'Child of')], default='UN', max_length=30)),
                ('param', models.IntegerField(default=1)),
                ('cardin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardin', to='scenarist.card')),
                ('cardout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardout', to='scenarist.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.epic'),
        ),
        migrations.AddField(
            model_name='card',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ChildrenCards', to='scenarist.card'),
        ),
    ]
