# Generated by Django 2.2 on 2020-10-31 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0018_auto_20201030_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='side_story',
        ),
        migrations.AddField(
            model_name='quizz',
            name='side_quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_quest', to='scenarist.QuizzAnswer'),
        ),
    ]
