# Generated by Django 3.2 on 2022-12-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0018_backlog_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='adventure',
        ),
    ]
