# Generated by Django 5.0 on 2025-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0019_alter_act_id_alter_adventure_id_alter_backlog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventure',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backlog',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drama',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epic',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
