# Generated by Django 4.1.4 on 2023-01-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0019_card_alter_drama_options_remove_act_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='abstract',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
