# Generated by Django 3.2 on 2022-12-10 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0020_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='adventure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.adventure'),
        ),
    ]
