# Generated by Django 5.0 on 2025-04-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0020_act_active_adventure_active_backlog_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['chapter', 'title']},
        ),
        migrations.AlterModelOptions(
            name='adventure',
            options={'ordering': ['chapter', 'title']},
        ),
        migrations.AlterModelOptions(
            name='backlog',
            options={'ordering': ['chapter', 'title']},
        ),
        migrations.AlterModelOptions(
            name='drama',
            options={'ordering': ['epic', 'chapter', 'date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='epic',
            options={'ordering': ['era', 'title']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['chapter', 'title']},
        ),
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['chapter', 'title']},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'ordering': ['chapter', 'title']},
        ),
        migrations.RenameField(
            model_name='act',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='adventure',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='backlog',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='drama',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='epic',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='scene',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='name',
            new_name='title',
        ),
    ]
