# Generated by Django 4.1.4 on 2023-01-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0021_card_sublevels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sublevels',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
