# Generated by Django 3.2 on 2022-12-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0021_scheme_adventure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='drama',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='epic',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='note',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='scene',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='card_type',
            field=models.CharField(choices=[('UN', 'Uncategorized'), ('SC', 'Scene'), ('EV', 'Event'), ('BK', 'Background'), ('AC', 'Act'), ('EP', 'Epic'), ('SH', 'Scheme'), ('AD', 'Adventure'), ('NO', 'Note'), ('DR', 'Drama')], default='UN', max_length=2),
        ),
    ]
