# Generated by Django 5.0 on 2025-05-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0021_alter_act_options_alter_adventure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='memorandum',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='adventure',
            name='session_part',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
