# Generated by Django 2.1 on 2018-12-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0021_auto_20181216_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128, unique=True),
        ),
    ]
