# Generated by Django 3.2 on 2022-12-12 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0022_auto_20221211_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.epic'),
        ),
    ]
