# Generated by Django 2.1 on 2018-12-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0022_auto_20181216_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='foes',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='epic',
            name='is_editable',
        ),
        migrations.RemoveField(
            model_name='epic',
            name='is_public',
        ),
        migrations.AddField(
            model_name='act',
            name='chapter',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='act',
            name='gamemaster',
            field=models.CharField(blank=True, default='zaffarelli@gmail.com', max_length=128),
        ),
        migrations.AddField(
            model_name='act',
            name='reward',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='epic',
            name='chapter',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='epic',
            name='date',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='epic',
            name='place',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='chapter',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='gamemaster',
            field=models.CharField(blank=True, default='zaffarelli@gmail.com', max_length=128),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='act',
            name='date',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='act',
            name='place',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='act',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='date',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='drama',
            name='place',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='epic',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='epic',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256, unique=True),
        ),
    ]
