# Generated by Django 2.2 on 2020-12-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0022_auto_20201107_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='epic',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
