# Generated by Django 2.1 on 2018-12-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0023_auto_20181225_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='anchor',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='event',
            name='estimated_gametime',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
