# Generated by Django 3.2 on 2022-12-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0023_note_epic'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='backlog',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='note',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
    ]
