# Generated by Django 2.1 on 2018-12-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0024_auto_20181228_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='foes',
        ),
        migrations.RemoveField(
            model_name='act',
            name='friends',
        ),
    ]
