# Generated by Django 4.1.4 on 2023-01-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0024_alter_challenge_options_challenge_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='current',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
