# Generated by Django 3.2 on 2022-12-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0024_auto_20221219_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Card',
        ),
    ]
