# Generated by Django 3.2 on 2022-12-22 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0025_rename_note_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('UN', 'Undefined'), ('PO', 'Parent of'), ('EX', 'Explains'), ('CO', 'consequence of')], default='UN', max_length=30)),
                ('param', models.IntegerField(default=1)),
                ('cardin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardin', to='scenarist.card')),
                ('cardout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardout', to='scenarist.card')),
            ],
        ),
    ]
