# Generated by Django 2.1 on 2018-12-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0025_auto_20181229_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['chapter', 'title']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['chapter', 'title']},
        ),
    ]
