# Generated by Django 4.1.4 on 2023-01-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0025_challenge_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='current',
            new_name='global_achievement',
        ),
    ]
