# Generated by Django 4.1.4 on 2023-01-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0026_rename_current_challenge_global_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(blank=True, default='', max_length=256)),
                ('completion', models.PositiveIntegerField(blank=True, default=1)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarist.challenge')),
            ],
            options={
                'ordering': ['line', 'completion'],
            },
        ),
    ]
