# Generated by Django 2.1 on 2019-01-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0026_auto_20181229_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='shortcut',
            field=models.CharField(blank=True, default='xx', max_length=32),
        ),
    ]
