# Generated by Django 4.1.4 on 2023-01-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0027_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='business_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='act',
            name='roleplay_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventure',
            name='business_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventure',
            name='roleplay_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backlog',
            name='business_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backlog',
            name='roleplay_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='business_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='roleplay_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drama',
            name='business_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drama',
            name='roleplay_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epic',
            name='business_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epic',
            name='roleplay_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='business_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='roleplay_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene',
            name='business_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene',
            name='roleplay_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='business_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='roleplay_scene',
            field=models.BooleanField(default=False),
        ),
    ]
