# Generated by Django 2.1 on 2019-01-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0027_epic_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2560),
        ),
        migrations.AlterField(
            model_name='drama',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2560),
        ),
        migrations.AlterField(
            model_name='epic',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2560),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2560),
        ),
    ]
