# Generated by Django 2.1 on 2019-03-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0028_auto_20190116_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='resolution',
            field=models.TextField(blank=True, default='', max_length=2560),
        ),
        migrations.AlterField(
            model_name='drama',
            name='resolution',
            field=models.TextField(blank=True, default='', max_length=2560),
        ),
        migrations.AlterField(
            model_name='event',
            name='resolution',
            field=models.TextField(blank=True, default='', max_length=2560),
        ),
    ]
