# Generated by Django 4.1.4 on 2023-01-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0028_act_business_scene_act_roleplay_scene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='mystery_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventure',
            name='mystery_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backlog',
            name='mystery_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='mystery_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drama',
            name='mystery_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epic',
            name='mystery_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='mystery_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene',
            name='mystery_scene',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='mystery_scene',
            field=models.BooleanField(default=False),
        ),
    ]
