# Generated by Django 4.1.4 on 2023-01-16 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0029_act_mystery_scene_adventure_mystery_scene_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='scenarist.card'),
        ),
    ]
