# Generated by Django 4.1.4 on 2023-01-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0030_alter_card_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventure',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backlog',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drama',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epic',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
