# Generated by Django 2.2.7 on 2020-01-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0031_auto_20200114_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='system',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
