# Generated by Django 2.2.7 on 2020-01-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0032_epic_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='image',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
