# Generated by Django 4.1.4 on 2023-01-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0033_card_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='plot_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='scenarist.card'),
        ),
    ]
