# Generated by Django 2.2.7 on 2020-01-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0034_auto_20200117_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='reward',
        ),
    ]
