# Generated by Django 4.1.4 on 2023-04-02 01:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0034_alter_challenge_plot_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='adventure',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='backlog',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='card',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scene',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scheme',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
    ]
