# Generated by Django 4.1.4 on 2023-04-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0036_alter_act_rewards_alter_adventure_rewards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='backlog',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
