# Generated by Django 4.1.4 on 2023-04-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0037_act_published_adventure_published_backlog_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drama',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epic',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scene',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
