# Generated by Django 4.1.4 on 2023-04-10 15:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0038_alter_act_published_alter_adventure_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scene',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='dramatis_personae',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
    ]
