# Generated by Django 4.1.4 on 2023-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0040_act_dp_adventure_dp_backlog_dp_card_dp_drama_dp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='dp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='dp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='dp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='dp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='dp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epic',
            name='dp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='dp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='dp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='dp',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
