version: "3.9"
services:
  dp_db:
    build:
      context: ../
      dockerfile: ./docker/postgres/Dockerfile
    restart: always
    container_name: dp_db
    environment:
      POSTGRES_DB: dramatis_personae
      POSTGRES_USER: dramatis_personae
      POSTGRES_PASSWORD_FILE: /run/secrets/dramatis_personae_db_passwd
    expose:
      - "5432"
    networks:
      - dp_db_net
    volumes:
      - db:/var/lib/postgresql/data
    secrets:
      - dramatis_personae_db_passwd

  dp_nginx:
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    container_name: dp_nginx
    restart: always
    ports:
      - "82:8087"
      - "443:44380"
    networks:
      - dp_web_net
    volumes:
      - static_files:/vol/web/static/
      - media_files:/vol/web/media/

  dp_web:
    build:
      context: ../
      dockerfile: ./docker/dramatis_personae/Dockerfile
    container_name: dp_web
    restart: always
    expose:
      - "8087"
    networks:
      - dp_db_net
      - dp_web_net
    environment:
      DEBUG: 0
      REGISTRATION_OPEN: 1
      DB_HOST: dp_db
      DB_PORT: "5432"
      DB_NAME: dramatis_personae
      DB_USER: dp
      DB_PASSWORD_FILE: /run/secrets/dramatis_personae_db_passwd
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      CORS_ALLOW_ALL_ORIGINS: 0
      CORS_ALLOWED_ORIGINS: "https://localhost,https://127.0.0.1,https://0.0.0.0"
    volumes:
      - static_files:/vol/web/static/
      - media_files:/vol/web/media/
    secrets:
      - dramatis_personae_db_passwd


volumes:
  db:
    name: dramatis_personae_db
  static_files:
    name: dramatis_personae_static_files
    driver_opts:
      type: tmpfs
      device: tmpfs
  media_files:
    name: dramatis_personae_media_files
    driver_opts:
      type: tmpfs
      device: tmpfs

secrets:
  dramatis_personae_db_passwd:
    file: ./secrets/dp_db_pass.txt

networks:
  dp_db_net:
    name: dp_db_net
    ipam:
      driver: default
    driver_opts:
      com.docker.network.bridge.name: dbr-dp_db

  dp_web_net:
    name: dp_web_net
    ipam:
      driver: default
    driver_opts:
      com.docker.network.bridge.name: dbr-dp_web
