# Generated by Django 4.1.4 on 2023-04-15 13:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrbitalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('0', 'Sun'), ('1', 'Gas Giant'), ('2', 'Telluric'), ('3', 'Asteroids Belt'), ('4', 'Space Station'), ('5', 'Jumpgate'), ('6', 'Allied Forces'), ('7', 'Hostiles')], default='Telluric', max_length=20)),
                ('color', colorfield.fields.ColorField(default='#FFF', image_field=None, max_length=18, samples=None)),
                ('azimut', models.FloatField(default=0)),
                ('distance', models.FloatField(default=0.0)),
                ('tilt', models.FloatField(default=0.0)),
                ('size', models.PositiveIntegerField(default=10)),
                ('qualifier', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('moon', models.TextField(blank=True, default='', max_length=1024, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=1024, null=True)),
                ('rings', models.TextField(blank=True, default='', max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Cartograph: Orbital Item',
                'ordering': ['system', 'distance'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('alliance', models.CharField(max_length=200)),
                ('sector', models.CharField(default='Empire', max_length=200)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('jump', models.IntegerField(default=0)),
                ('group', models.IntegerField(default=0)),
                ('color', colorfield.fields.ColorField(default='#CCC', image_field=None, max_length=18, samples=None)),
                ('dtj', models.FloatField(default=69)),
                ('garrison', models.IntegerField(default=1)),
                ('tech', models.IntegerField(default=3)),
                ('population', models.IntegerField(default=0)),
                ('discovery', models.IntegerField(default=6000)),
                ('symbol', models.CharField(default='9', max_length=1)),
                ('zoom_val', models.IntegerField(blank=True, default=0, null=True)),
                ('zoom_factor', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Cartograph: System',
                'ordering': ['name'],
            },
        ),
    ]
