# Generated by Django 4.1.4 on 2023-04-12 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartograph', '0001_initial'),
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='allianceref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.allianceref'),
        ),
        migrations.AddField(
            model_name='system',
            name='jumproads',
            field=models.ManyToManyField(blank=True, to='cartograph.system'),
        ),
        migrations.AddField(
            model_name='orbitalitem',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartograph.system'),
        ),
    ]
