# Generated by Django 2.2 on 2021-11-07 11:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='color',
            field=colorfield.fields.ColorField(default='#CCC', max_length=18),
        ),
    ]
