# Generated by Django 2.2 on 2021-11-07 11:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0002_auto_20211107_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbitalitem',
            name='color',
            field=colorfield.fields.ColorField(default='#FFF', max_length=18),
        ),
    ]
