# Generated by Django 2.2 on 2022-01-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0005_system_allianceref'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
