# Generated by Django 4.1.4 on 2022-12-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0006_system_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='jumproads',
            field=models.ManyToManyField(blank=True, to='cartograph.system'),
        ),
    ]
