# Generated by Django 5.0.6 on 2024-09-12 01:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0006_system_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbitalitem',
            name='color',
            field=colorfield.fields.ColorField(default='#FFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='system',
            name='color',
            field=colorfield.fields.ColorField(default='#CCC', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='system',
            name='jumproads',
            field=models.ManyToManyField(blank=True, to='cartograph.system'),
        ),
    ]
