# Generated by Django 5.0.6 on 2024-09-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0007_alter_orbitalitem_color_alter_system_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbitalitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='system',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
