# Generated by Django 5.0 on 2024-10-25 07:34

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0008_alter_orbitalitem_id_alter_system_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbitalitem',
            name='azimut',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='orbitalitem',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='orbitalitem',
            name='distance',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='orbitalitem',
            name='size',
            field=models.PositiveIntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='orbitalitem',
            name='tilt',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
