# Generated by Django 5.0 on 2024-10-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0009_alter_orbitalitem_azimut_alter_orbitalitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='notes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
