# Generated by Django 5.0 on 2024-10-26 13:54

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0010_system_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='alliance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='system',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#CCC', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='system',
            name='discovery',
            field=models.IntegerField(blank=True, default=6000),
        ),
        migrations.AlterField(
            model_name='system',
            name='dtj',
            field=models.FloatField(blank=True, default=69),
        ),
        migrations.AlterField(
            model_name='system',
            name='garrison',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='system',
            name='group',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='system',
            name='jump',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='system',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='system',
            name='population',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='system',
            name='sector',
            field=models.CharField(blank=True, default='Empire', max_length=200),
        ),
        migrations.AlterField(
            model_name='system',
            name='symbol',
            field=models.CharField(blank=True, default='9', max_length=1),
        ),
        migrations.AlterField(
            model_name='system',
            name='tech',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='system',
            name='x',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='system',
            name='y',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
