# Generated by Django 5.0 on 2024-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0011_alter_system_alliance_alter_system_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orbitalitem',
            options={'ordering': ['system_rid', 'distance'], 'verbose_name': 'Cartograph: Orbital Item'},
        ),
        migrations.RemoveField(
            model_name='orbitalitem',
            name='system',
        ),
        migrations.RemoveField(
            model_name='system',
            name='allianceref',
        ),
        migrations.AddField(
            model_name='orbitalitem',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='orbitalitem',
            name='system_rid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='system',
            name='alliance_rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='system',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='system',
            name='alliance',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
