# Generated by Django 5.0 on 2024-10-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0012_alter_orbitalitem_options_remove_orbitalitem_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbitalitem',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='system',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
