# Generated by Django 5.0 on 2025-01-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0013_alter_orbitalitem_rid_alter_system_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitalitem',
            name='system',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
