# Generated by Django 5.0 on 2025-04-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0014_orbitalitem_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitalitem',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='system',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
