# Generated by Django 5.0 on 2025-04-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0015_orbitalitem_cypher_rid_system_cypher_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbitalitem',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='system',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
