# Generated by Django 2.0.2 on 2018-02-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='PA_AGI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='PA_AWA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='PA_BOD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='PA_CON',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='PA_INT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='PA_MOV',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='PA_PRE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='PA_REF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='PA_STR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='PA_TEC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='PA_TEM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='PA_WIL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='alliance',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
