# Generated by Django 2.2.7 on 2020-03-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='keyword',
            field=models.CharField(blank=True, default='new', max_length=32),
        ),
    ]
