# Generated by Django 2.2 on 2021-03-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='epic',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='epic',
        ),
    ]
