# Generated by Django 2.1 on 2019-02-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponref',
            name='stats',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
