# Generated by Django 2.1 on 2019-03-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casteveryman',
            options={'ordering': ['species', 'race']},
        ),
        migrations.RenameField(
            model_name='casteveryman',
            old_name='reference',
            new_name='species',
        ),
        migrations.AlterUniqueTogether(
            name='casteveryman',
            unique_together={('species', 'race')},
        ),
    ]
