# Generated by Django 2.2.7 on 2019-12-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.CharacterCusto')),
                ('weapon_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.WeaponRef')),
            ],
            options={
                'ordering': ['character_custo', 'weapon_ref'],
            },
        ),
        migrations.CreateModel(
            name='ShieldCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.CharacterCusto')),
                ('shield_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.ShieldRef')),
            ],
            options={
                'ordering': ['character_custo', 'shield_ref'],
            },
        ),
        migrations.CreateModel(
            name='ArmorCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.ArmorRef')),
                ('character_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.CharacterCusto')),
            ],
            options={
                'ordering': ['character_custo', 'armor_ref'],
            },
        ),
    ]
