# Generated by Django 2.0.2 on 2018-05-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_squashed_0022_skill_ordo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='rid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
