# Generated by Django 4.1.4 on 2023-04-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='campaign',
        ),
    ]
