# Generated by Django 4.1.4 on 2023-04-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_remove_profile_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='current_fief',
        ),
        migrations.RemoveField(
            model_name='character',
            name='fief',
        ),
        migrations.RemoveField(
            model_name='character',
            name='native_fief',
        ),
    ]
