# Generated by Django 2.0.2 on 2018-05-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20180505_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='occult',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='occult_darkside',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='occult_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
