# Generated by Django 2.1 on 2019-02-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_weaponref_stats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weaponref',
            options={'ordering': ['reference', 'category', 'damage_class']},
        ),
    ]
