# Generated by Django 2.1 on 2019-03-28 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_remove_character_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weaponref',
            options={'ordering': ['origins', 'reference', 'category', 'damage_class']},
        ),
    ]
