# Generated by Django 2.2.7 on 2019-11-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20191123_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficeAfflictionModificator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficeaffliction_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.BeneficeAfflictionRef')),
                ('tour_of_duty_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.TourOfDutyRef')),
            ],
            options={
                'ordering': ['beneficeaffliction_ref'],
            },
        ),
    ]
