# Generated by Django 2.2.7 on 2020-03-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20200319_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('sleeves_authenticity', models.PositiveIntegerField(default=0)),
                ('sleeves_gossip', models.PositiveIntegerField(default=0)),
                ('sleeves_fame', models.PositiveIntegerField(default=0)),
                ('sleeves_auction', models.PositiveIntegerField(default=100)),
                ('sleeves_minimum_increment', models.PositiveIntegerField(default=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.Character')),
            ],
        ),
    ]
