# Generated by Django 2.2 on 2019-04-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20190422_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
