# Generated by Django 2.2.7 on 2019-12-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_armorcusto_shieldcusto_weaponcusto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='caste',
            field=models.CharField(blank=True, choices=[('Nobility', 'Nobility'), ('Church', 'Church'), ('Guild', 'Guild'), ('Alien', 'Alien'), ('Other', 'Other'), ('Freefolk', 'Freefolk')], default='Other', max_length=20),
        ),
    ]
