# Generated by Django 2.1 on 2019-03-03 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_casteveryman_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='castspecies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.CastEveryman'),
        ),
    ]
