# Generated by Django 2.1 on 2019-03-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20190328_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shieldref',
            options={'ordering': ['cost', 'reference']},
        ),
    ]
