# Generated by Django 2.2 on 2019-05-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_character_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillref',
            name='is_common',
            field=models.BooleanField(default=True),
        ),
    ]
