# Generated by Django 2.2.10 on 2020-05-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20200511_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipref',
            name='firebirds',
            field=models.IntegerField(default=0),
        ),
    ]
