# Generated by Django 2.2.7 on 2019-11-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_beneficeafflictionmodificator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficeafflictionmodificator',
            options={'ordering': ['benefice_affliction_ref']},
        ),
        migrations.RenameField(
            model_name='beneficeafflictionmodificator',
            old_name='beneficeaffliction_ref',
            new_name='benefice_affliction_ref',
        ),
    ]
