# Generated by Django 2.1 on 2019-03-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20190325_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='is_locked',
            new_name='locked',
        ),
    ]
