# Generated by Django 2.2.7 on 2020-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_loot'),
    ]

    operations = [
        migrations.AddField(
            model_name='loot',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
