# Generated by Django 2.0.2 on 2018-02-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20180210_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='SA_REC',
            field=models.IntegerField(default=0),
        ),
    ]
