# Generated by Django 2.1 on 2019-03-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20190326_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='locked',
            new_name='is_locked',
        ),
    ]
