# Generated by Django 2.1 on 2019-03-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_character_castspecies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='species',
        ),
    ]
