# Generated by Django 2.0.2 on 2018-02-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_character_sa_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='SA_DMG',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='SA_END',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='SA_HUM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='SA_PAS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='SA_RES',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='SA_RUN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='SA_SPD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='SA_STA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='SA_STU',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='SA_TOL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='SA_WYR',
            field=models.IntegerField(default=0),
        ),
    ]
