# Generated by Django 2.2 on 2019-05-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_skillref_is_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='skill_roots',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
