# Generated by Django 4.1.4 on 2023-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_remove_spaceship_registration_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceref',
            name='hook',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='allianceref',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='hook',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='skillref',
            name='hook',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
