# Generated by Django 2.1 on 2019-02-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_skillref_custom_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.CharField(choices=[('tech', 'Tech'), ('physical', 'Physical'), ('spiritual', 'Spiritual'), ('standard', 'Standard'), ('courtisan', 'Courtisan'), ('scholar', 'Scholar'), ('guilder', 'Guilder'), ('diplomat', 'Diplomat'), ('undefined', 'Undefined')], default='undefined', max_length=16),
        ),
    ]
