# Generated by Django 2.2.7 on 2019-12-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_skillref_is_wildcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorref',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
