# Generated by Django 2.2.7 on 2019-11-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20191123_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='caste',
            field=models.CharField(blank=True, choices=[('Nobility', 'Nobility'), ('Church', 'Church'), ('Guild', 'Guild'), ('Alien', 'Alien'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='category',
            field=models.CharField(blank=True, choices=[('Upbringing', 'Upbringing'), ('Apprenticeship', 'Apprenticeship'), ('Early Career', 'Early Career'), ('Tour of Duty', 'Tour of Duty'), ('Full Tour of Duty', 'Full Tour of Duty')], default='Tour of Duty', max_length=20),
        ),
    ]
