# Generated by Django 2.2.10 on 2020-05-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_shipref_firebirds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipsystem',
            old_name='cost',
            new_name='firebirds',
        ),
        migrations.RenameField(
            model_name='shipsystem',
            old_name='cost_per_rating',
            new_name='firebirds_per_rating',
        ),
    ]
