# Generated by Django 2.1 on 2019-03-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20190330_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castrole',
            options={'ordering': ['value', 'reference']},
        ),
    ]
