# Generated by Django 2.2.7 on 2019-12-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20191231_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorref',
            name='tech_level',
            field=models.PositiveIntegerField(blank=True, default=3),
        ),
    ]
