# Generated by Django 2.1 on 2019-04-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20190330_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
