# Generated by Django 2.2 on 2021-03-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20210322_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='br_tod_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='specie',
            name='ra_tod_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
