# Generated by Django 2.0.2 on 2018-04-28 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20180217_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date published'),
        ),
    ]
