# Generated by Django 2.2 on 2019-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_role_skill_roots'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.CharField(default='[]', max_length=640),
        ),
    ]
