# Generated by Django 2.2.7 on 2019-11-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20191123_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='source',
            field=models.CharField(blank=True, default='FS2CRB', max_length=32, null=True),
        ),
    ]
