# Generated by Django 4.1.4 on 2023-04-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_allianceref_hook_allianceref_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allianceref',
            name='hook',
        ),
        migrations.RemoveField(
            model_name='beneficeafflictionref',
            name='hook',
        ),
        migrations.RemoveField(
            model_name='skillref',
            name='hook',
        ),
    ]
