# Generated by Django 2.1 on 2019-02-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20190219_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillref',
            name='group',
            field=models.CharField(choices=[('EDU', 'Education'), ('FIG', 'Combat'), ('AWA', 'Awareness'), ('BOD', 'Physical'), ('TIN', 'Tinkering'), ('PER', 'Performance'), ('SOC', 'Social'), ('CON', 'Control'), ('UND', 'Underworld')], default='EDU', max_length=3),
        ),
    ]
