# Generated by Django 2.1 on 2019-03-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_casteveryman_attr_mod_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='casteveryman',
            name='skill_balance',
            field=models.IntegerField(default=0),
        ),
    ]
