# Generated by Django 4.1.4 on 2023-04-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_remove_allianceref_hook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'References: User Profile'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='main_character',
        ),
    ]
