# Generated by Django 2.2 on 2019-05-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_profile_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('AP', models.IntegerField(default=0)),
                ('OP', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
    ]
