# Generated by Django 2.2 on 2021-03-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_auto_20210326_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='br_tod_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='specie',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='specie',
            name='ra_tod_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
