# Generated by Django 2.0.2 on 2018-05-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_auto_20180505_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='BC_TOTAL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='TA_TOTAL',
            field=models.IntegerField(default=0),
        ),
    ]
