# Generated by Django 2.2.7 on 2020-03-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_loot_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loot',
            name='group',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
