# Generated by Django 2.2.7 on 2019-11-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_tourofdutyref_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='blessingcurseref',
            name='source',
            field=models.CharField(blank=True, default='FS2CRB', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='use_history_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='beneficeafflictionref',
            name='source',
            field=models.CharField(blank=True, default='FS2CRB', max_length=32, null=True),
        ),
    ]
