# Generated by Django 2.2.7 on 2019-11-24 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20191124_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourOfDuty',
        ),
    ]
