# Generated by Django 2.0.2 on 2018-05-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20180505_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillref',
            name='linked_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.SkillRef'),
        ),
    ]
