# Generated by Django 2.0.2 on 2018-04-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_character_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='PA_TOTAL',
            field=models.IntegerField(default=0),
        ),
    ]
