# Generated by Django 2.2.7 on 2020-03-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20200320_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='loot',
            name='session',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
