# Generated by Django 2.1 on 2019-04-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_character_is_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='use_only_entrance',
            field=models.BooleanField(default=True),
        ),
    ]
