# Generated by Django 2.2.10 on 2020-05-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20200511_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipref',
            name='ship_status',
            field=models.CharField(choices=[('wip', 'Work In Progress'), ('combat_ready', 'Combat Ready')], default='wip', max_length=10),
        ),
    ]
