# Generated by Django 2.2.7 on 2019-12-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20191231_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponref',
            name='meta_type',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
