# Generated by Django 2.2 on 2021-03-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20210326_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='combat',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='mental',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='physical',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
