# Generated by Django 2.1 on 2019-02-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20190221_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.CharField(choices=[('tech', 'Tech'), ('physical', 'Physical'), ('spiritual', 'Spiritual'), ('standard', 'Standard'), ('courtisan', 'Courtisan'), ('scholar', 'Scholar'), ('guilder', 'Guilder'), ('diplomat', 'Diplomat'), ('bully', 'Bully'), ('undefined', 'Undefined')], default='undefined', max_length=16),
        ),
        migrations.AlterField(
            model_name='skillref',
            name='group',
            field=models.CharField(choices=[('AWA', 'Awareness'), ('BOD', 'Physical'), ('CON', 'Control'), ('DIP', 'Diplomacy'), ('EDU', 'Education'), ('FIG', 'Combat'), ('PER', 'Performance'), ('SOC', 'Social'), ('SPI', 'Spirituality'), ('TIN', 'Tinkering'), ('UND', 'Underworld')], default='EDU', max_length=3),
        ),
    ]
