# Generated by Django 2.2 on 2019-05-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_talentref'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='talent_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collector.TalentRef'),
        ),
    ]
