# Generated by Django 2.2.7 on 2019-11-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_delete_tourofduty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillref',
            options={'ordering': ['is_speciality', 'reference'], 'verbose_name': 'Skill Reference'},
        ),
        migrations.AlterModelOptions(
            name='talentref',
            options={'ordering': ['reference'], 'verbose_name': 'Talent Reference'},
        ),
        migrations.AlterModelOptions(
            name='tourofdutyref',
            options={'ordering': ['reference'], 'verbose_name': 'Tour of Duty Reference'},
        ),
        migrations.AlterModelOptions(
            name='weaponref',
            options={'ordering': ['origins', 'reference', 'category', 'damage_class'], 'verbose_name': 'Weapon Reference'},
        ),
    ]
