# Generated by Django 2.2.7 on 2020-01-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_weaponref_meta_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='WP',
            field=models.IntegerField(default=0),
        ),
    ]
