# Generated by Django 2.2 on 2019-05-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_talent_talent_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentref',
            options={'ordering': ['value', 'reference']},
        ),
    ]
