# Generated by Django 2.0.2 on 2018-05-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_skillref_linked_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='challenge',
            field=models.TextField(blank=True, default=''),
        ),
    ]
