# Generated by Django 2.2.10 on 2020-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_shipref_ship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipsection',
            name='slot',
            field=models.CharField(blank=True, choices=[('0', 'Fore'), ('1', 'Fore Port'), ('2', 'Port'), ('3', 'Aft Port'), ('4', 'Aft'), ('5', 'Aft Starboard'), ('6', 'Starboard'), ('7', 'Fore Starboard')], default='Fore', max_length=30, null=True),
        ),
    ]
