# Generated by Django 2.1 on 2019-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_auto_20190309_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casteveryman',
            name='racial_attr_mod',
            field=models.CharField(default='{}', max_length=128),
        ),
        migrations.AlterField(
            model_name='casteveryman',
            name='racial_occult',
            field=models.CharField(default='{}', max_length=128),
        ),
        migrations.AlterField(
            model_name='casteveryman',
            name='racial_skills',
            field=models.CharField(default='{}', max_length=512),
        ),
    ]
