# Generated by Django 2.1 on 2019-02-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_auto_20190221_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillref',
            options={'ordering': ['is_speciality', 'reference']},
        ),
    ]
