# Generated by Django 2.0.2 on 2018-04-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_character_pa_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alliance',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.CharField(default='', max_length=200),
        ),
    ]
