# Generated by Django 2.0.2 on 2018-05-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_character_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillref',
            name='linked_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.SkillRef'),
        ),
    ]
