# Generated by Django 2.2.7 on 2020-01-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_tourofdutyref_wp'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='balanced',
            field=models.BooleanField(default=False),
        ),
    ]
