# Generated by Django 2.2 on 2021-03-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_character_tod_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='storytelling_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
