# Generated by Django 2.2.7 on 2020-03-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_auto_20200320_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loot',
            name='code',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
