# Generated by Django 2.2 on 2019-05-05 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_auto_20190505_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentref',
            options={'ordering': ['reference']},
        ),
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.Profile'),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.Role'),
        ),
        migrations.AlterField(
            model_name='character',
            name='specie',
            field=models.ForeignKey(blank=True, default=22, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.Specie'),
        ),
    ]
