# Generated by Django 2.0.2 on 2018-04-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_auto_20180428_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='PA_AGI',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_AWA',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_BOD',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_CON',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_INT',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_MOV',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_PRE',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_REF',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_STR',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_TEC',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_TEM',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_WIL',
            field=models.IntegerField(default=3),
        ),
    ]
