# Generated by Django 2.2.10 on 2020-05-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_auto_20200511_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipsection',
            name='section',
            field=models.CharField(blank=True, choices=[('0', 'Bridge'), ('1', 'Maneuver'), ('2', 'Gundeck'), ('3', 'Engine Room'), ('4', 'Marines Deck'), ('5', 'Turret A'), ('6', 'Turret B'), ('7', 'Turret Z'), ('8', 'Spinal Mount'), ('9', 'Shieldbank'), ('10', 'Troop Quarters')], default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shipsection',
            name='slot',
            field=models.CharField(blank=True, choices=[('0', 'Fore'), ('1', 'Fore Port'), ('2', 'Port'), ('3', 'Aft Port'), ('4', 'Aft'), ('5', 'Aft Starboard'), ('6', 'Starboard'), ('7', 'Fore Starboard')], default='1', max_length=30, null=True),
        ),
    ]
