# Generated by Django 2.1 on 2019-04-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_auto_20190404_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='use_only_entrance',
            field=models.BooleanField(default=False),
        ),
    ]
