# Generated by Django 2.2.7 on 2020-01-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_character_balanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='emphasis',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
