# Generated by Django 2.2 on 2019-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20190405_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='keyword',
            field=models.CharField(blank=True, default='other', max_length=32),
        ),
    ]
