# Generated by Django 2.2.7 on 2019-11-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20191124_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='category',
            field=models.CharField(blank=True, choices=[('Race', 'Race'), ('Upbringing', 'Upbringing'), ('Apprenticeship', 'Apprenticeship'), ('Early Career', 'Early Career'), ('Tour of Duty', 'Tour of Duty'), ('Worldly Benefits', 'Worldly Benefits')], default='Tour of Duty', max_length=20),
        ),
    ]
