# Generated by Django 2.2.7 on 2020-03-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20200320_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='loot',
            name='secret',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
