# Generated by Django 2.0.2 on 2018-04-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20180428_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='narrative',
            field=models.TextField(default=''),
        ),
    ]
