# Generated by Django 2.2 on 2021-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_character_storytelling_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='attr_mod_balance',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='racial_attr_mod',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='racial_occult',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='racial_skills',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='skill_balance',
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='caliber',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='origins',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='stats',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
