# Generated by Django 2.2 on 2019-05-05 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20190505_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='specie',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.Specie'),
        ),
    ]
