# Generated by Django 2.0.2 on 2018-05-05 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20180505_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammoes', models.PositiveIntegerField(blank=True, default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Character')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('category', models.CharField(blank=True, default='RIF', max_length=16)),
                ('wa', models.IntegerField(blank=True, default=0)),
                ('conceilable', models.CharField(blank=True, default='Jacket', max_length=16)),
                ('availability', models.CharField(blank=True, default='CO', max_length=16)),
                ('damage_class', models.CharField(blank=True, default='1d6', max_length=16)),
                ('caliber', models.CharField(blank=True, default='', max_length=16)),
                ('str_min', models.PositiveIntegerField(blank=True, default=0)),
                ('rof', models.PositiveIntegerField(blank=True, default=0)),
                ('clip', models.PositiveIntegerField(blank=True, default=0)),
                ('rng', models.PositiveIntegerField(blank=True, default=0)),
                ('rel', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.WeaponRef'),
        ),
    ]
