# Generated by Django 2.1 on 2019-03-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_character_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
