# Generated by Django 2.2 on 2021-03-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_auto_20210327_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='caste',
            field=models.CharField(choices=[('Nobility', 'Nobility'), ('Church', 'Church'), ('Guild', 'Guild'), ('Alien', 'Alien'), ('Other', 'Other'), ('Freefolk', 'Freefolk'), ('Think Machine', 'Think Machine')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='category',
            field=models.CharField(choices=[('0', 'Birthright'), ('5', 'Balance'), ('10', 'Upbringing'), ('20', 'Apprenticeship'), ('30', 'Early Career'), ('40', 'Tour of Duty'), ('50', 'Worldly Benefits'), ('60', 'Nameless Kit'), ('70', 'Build')], default='Tour of Duty', max_length=20),
        ),
    ]
