# Generated by Django 2.2.10 on 2020-05-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_auto_20200512_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipref',
            name='ship_status',
            field=models.CharField(choices=[('wip', 'Work In Progress'), ('combat_ready', 'Combat Ready'), ('invalid_sections', 'Invalid Sections')], default='wip', max_length=30),
        ),
    ]
