# Generated by Django 2.1 on 2019-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_auto_20190302_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
