# Generated by Django 2.0.2 on 2018-04-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_character_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='birthdate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='caste',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(default='male', max_length=30),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='character',
            name='native_fief',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='rank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.CharField(default='urthish', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.IntegerField(default=50),
        ),
    ]
