# Generated by Django 2.2.7 on 2020-03-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_loot_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='character',
            name='role',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
