# Generated by Django 2.0.2 on 2018-05-05 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_auto_20180505_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArmorRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('category', models.CharField(blank=True, default='SOFT', max_length=16)),
                ('head', models.BooleanField(default=True)),
                ('torso', models.BooleanField(default=True)),
                ('left_arm', models.BooleanField(default=True)),
                ('right_arm', models.BooleanField(default=True)),
                ('left_leg', models.BooleanField(default=True)),
                ('right_leg', models.BooleanField(default=True)),
                ('stopping_power', models.PositiveIntegerField(blank=True, default=2)),
            ],
        ),
        migrations.AddField(
            model_name='armor',
            name='armor_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.ArmorRef'),
        ),
        migrations.AddField(
            model_name='armor',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Character'),
        ),
    ]
