# Generated by Django 2.2 on 2019-04-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_auto_20190420_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='alliance_picture',
        ),
        migrations.RemoveField(
            model_name='character',
            name='build_log',
        ),
        migrations.RemoveField(
            model_name='character',
            name='picture',
        ),
    ]
