# Generated by Django 2.2.7 on 2020-01-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_auto_20200109_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gm_shortcuts_pdf',
            field=models.TextField(blank=True, default=''),
        ),
    ]
