# Generated by Django 2.2.7 on 2020-03-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_auto_20200322_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='category',
            field=models.CharField(blank=True, choices=[('00', 'Birthright'), ('10', 'Upbringing'), ('20', 'Apprenticeship'), ('30', 'Early Career'), ('40', 'Tour of Duty'), ('50', 'Worldly Benefits')], default='Tour of Duty', max_length=20),
        ),
    ]
