# Generated by Django 2.2.10 on 2020-05-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_auto_20200512_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipsection',
            name='section',
            field=models.CharField(blank=True, choices=[('0', 'Bridge'), ('1', 'Maneuver'), ('2', 'Gundeck'), ('3', 'Engine Room'), ('4', 'Marines Deck'), ('5', 'Turret A'), ('6', 'Turret B'), ('7', 'Turret Z'), ('8', 'Spinal Mount'), ('9', 'Shieldbank'), ('10', 'Troop Quarters'), ('11', 'Battleshield')], default='0', max_length=30, null=True),
        ),
    ]
