# Generated by Django 2.1 on 2019-03-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_character_is_dead'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='CastProfile',
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='CastRole',
        ),
    ]
