# Generated by Django 2.2.7 on 2019-11-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_auto_20191124_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourOfDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Character')),
                ('tour_of_duty_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.TourOfDutyRef')),
            ],
            options={
                'ordering': ['character', 'tour_of_duty_ref'],
            },
        ),
    ]
