# Generated by Django 2.2 on 2021-03-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_auto_20210327_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='need_fix',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
