# Generated by Django 2.1 on 2019-03-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_auto_20190303_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='castrole',
            name='mini',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
