# Generated by Django 2.0.2 on 2018-04-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_character_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alliance',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='caste',
            field=models.CharField(default='Freefolk', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='narrative',
            field=models.TextField(default='...'),
        ),
        migrations.AlterField(
            model_name='character',
            name='native_fief',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='rank',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
