# Generated by Django 2.2.7 on 2020-02-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_character_gm_shortcuts_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillref',
            options={'ordering': ['is_speciality', 'is_wildcard', 'reference'], 'verbose_name': 'Skill Reference'},
        ),
    ]
