# Generated by Django 2.2.7 on 2019-11-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_tourofduty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='PA_AGI',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_AWA',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_BOD',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_CON',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_INT',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_MOV',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_PRE',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_REF',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_STR',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_TEC',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_TEM',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_WIL',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='category',
            field=models.CharField(blank=True, choices=[('00_Race', 'Race'), ('01_Upbringing', 'Upbringing'), ('02_Apprenticeship', 'Apprenticeship'), ('03_Early Career', 'Early Career'), ('04_Tour of Duty', 'Tour of Duty'), ('05_Worldly Benefits', 'Worldly Benefits')], default='Tour of Duty', max_length=20),
        ),
    ]
