# Generated by Django 2.2.10 on 2020-05-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_auto_20200512_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipsystem',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'Engine'), ('1', 'Jumpdrive'), ('2', 'Shield'), ('3', 'Sensor'), ('4', 'Turret'), ('5', 'Direct Fire Weapon'), ('6', 'Indirect Fire Weapon'), ('7', 'Miscellaneous'), ('8', 'Transmissions'), ('9', 'Crew')], default='Miscellaneous', max_length=20),
        ),
    ]
