# Generated by Django 2.0.2 on 2018-05-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_character_ready_for_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gm_shortcuts',
            field=models.TextField(blank=True, default=''),
        ),
    ]
