# Generated by Django 2.2.7 on 2019-11-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_auto_20191124_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='category',
            field=models.CharField(blank=True, choices=[('00_Race', '00_Race'), ('01_Upbringing', '01_Upbringing'), ('02_Apprenticeship', '02_Apprenticeship'), ('03_Early Career', '03_Early Career'), ('04_Tour of Duty', '04_Tour of Duty'), ('05_Worldly Benefits', '05_Worldly Benefits')], default='Tour of Duty', max_length=20),
        ),
    ]
