# Generated by Django 2.0 on 2018-05-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_auto_20180429_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='caste',
            field=models.CharField(blank=True, default='Freefolk', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='native_fief',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='rank',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
