# Generated by Django 2.0.2 on 2018-05-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_character_gm_shortcuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponref',
            name='conceilable',
            field=models.CharField(blank=True, choices=[('P', 'Pocket'), ('J', 'Jacket'), ('L', 'Long coat'), ('N', "can't be hidden")], default='J', max_length=1),
        ),
    ]
