# Generated by Django 2.2.7 on 2020-02-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_auto_20200207_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.CharField(blank=True, default='#CCCCCC', max_length=20),
        ),
    ]
