# Generated by Django 2.2.10 on 2020-05-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_auto_20200512_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipsection',
            name='section_id',
        ),
    ]
