# Generated by Django 2.2.7 on 2020-03-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_auto_20200322_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourofdutyref',
            options={'ordering': ['category', 'reference'], 'verbose_name': 'Tour of Duty Reference'},
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_exportable',
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'Birthright'), ('5', 'Balance'), ('10', 'Upbringing'), ('20', 'Apprenticeship'), ('30', 'Early Career'), ('40', 'Tour of Duty'), ('50', 'Worldly Benefits')], default='Tour of Duty', max_length=20),
        ),
    ]
