# Generated by Django 2.2 on 2021-03-28 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_tourofdutyref_need_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date published'),
        ),
    ]
