# Generated by Django 2.1 on 2019-03-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_castrole_mini'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='castprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.CastProfile'),
        ),
        migrations.AddField(
            model_name='character',
            name='castrole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.CastRole'),
        ),
    ]
