# Generated by Django 2.1 on 2019-03-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_auto_20190303_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='character',
            name='role',
        ),
        migrations.AlterField(
            model_name='castprofile',
            name='reference',
            field=models.CharField(blank=True, default='new_profile', max_length=64, unique=True),
        ),
    ]
