# Generated by Django 2.2.7 on 2019-11-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_auto_20191124_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'Race'), ('1', 'Upbringing'), ('2', 'Apprenticeship'), ('3', 'Early Career'), ('4', 'Tour of Duty'), ('5', 'Worldly Benefits')], default='Tour of Duty', max_length=20),
        ),
    ]
