# Generated by Django 2.2 on 2021-03-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_tourofdutyref_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='category',
            field=models.CharField(choices=[('0', 'Birthright'), ('5', 'Balance'), ('10', 'Upbringing'), ('20', 'Apprenticeship'), ('30', 'Early Career'), ('40', 'Tour of Duty'), ('50', 'Worldly Benefits'), ('60', 'Nameless Kit'), ('70', 'Build'), ('80', 'Custom')], default='Tour of Duty', max_length=20),
        ),
    ]
