# Generated by Django 2.0.2 on 2018-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_auto_20180512_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weaponref',
            old_name='wa',
            new_name='weapon_accuracy',
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='availability',
            field=models.CharField(blank=True, choices=[('E', 'Excellent'), ('C', 'Commmon'), ('P', 'Poor'), ('R', 'Rare')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='category',
            field=models.CharField(blank=True, choices=[('MELEE', 'Melee weapon'), ('P', 'Pistol/revolver'), ('RIF', 'Rifle'), ('SMG', 'Submachinegun'), ('SHG', 'Shotgun'), ('HVY', 'Heavy weapon'), ('EX', 'Exotic weapon')], default='RIF', max_length=5),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='conceilable',
            field=models.CharField(blank=True, choices=[('P', 'Pocket'), ('J', 'Jacket'), ('L', 'Long coat'), ('N', "Can't be hidden")], default='J', max_length=1),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='rel',
            field=models.CharField(blank=True, choices=[('VR', 'Very reliable'), ('ST', 'Standard'), ('UR', 'Unreliable')], default='ST', max_length=2),
        ),
    ]
