# Generated by Django 2.2.10 on 2020-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_remove_shipsection_section_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipref',
            old_name='marines',
            new_name='crew_marines',
        ),
        migrations.AddField(
            model_name='shipref',
            name='crew_engineers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='crew_gunners',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='crew_jetjockeys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='crew_marauders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='crew_pilots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
