# Generated by Django 2.2.7 on 2020-03-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_auto_20200323_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spotlight',
            field=models.BooleanField(default=False),
        ),
    ]
