# Generated by Django 2.2.7 on 2020-02-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_character_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='importance',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
