# Generated by Django 2.2.7 on 2020-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_character_spotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='todo_list',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.CharField(blank=True, default='https://drive.google.com/file/d/15hdubdMt1t_deSXkbg9dsAjWi5tZwMU0/view', max_length=256),
        ),
    ]
