# Generated by Django 2.0 on 2018-05-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_auto_20180502_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='entrance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
