# Generated by Django 2.0.2 on 2018-05-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_auto_20180512_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponref',
            name='availability',
            field=models.CharField(blank=True, choices=[('E', 'Excellent'), ('C', 'Common'), ('P', 'Poor'), ('R', 'Rare')], default='C', max_length=1),
        ),
    ]
