# Generated by Django 2.2.7 on 2020-02-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_character_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='victories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
