# Generated by Django 2.2 on 2021-03-28 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_auto_20210328_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberwareref',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date published'),
        ),
    ]
