# Generated by Django 2.2.10 on 2020-05-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_auto_20200514_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsection',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='_shipsection_links_+', to='collector.ShipSection'),
        ),
    ]
