# Generated by Django 2.2.10 on 2020-05-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_shipsection_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbitalitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
