# Generated by Django 2.2.7 on 2019-12-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_auto_20191203_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='topic',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
