# Generated by Django 2.0.2 on 2018-05-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_character_entrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_speciality',
            field=models.BooleanField(default=False),
        ),
    ]
