# Generated by Django 2.2 on 2021-03-28 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_cyberwareref_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberfeature',
            name='need_fix',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='cyberfeature',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date published'),
        ),
    ]
