# Generated by Django 2.0.2 on 2018-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_auto_20180512_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='ordo',
        ),
        migrations.AddField(
            model_name='armorref',
            name='description',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='category',
            field=models.CharField(blank=True, choices=[('SOFT', 'Soft Armor'), ('MEDIUM', 'Medium Armor'), ('HARD', 'Hard Armor')], default='SOFT', max_length=5),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='left_leg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='right_leg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='alliance',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(default='female', max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
