# Generated by Django 2.2.7 on 2020-02-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_auto_20200221_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='victory_rating',
            field=models.IntegerField(default=0),
        ),
    ]
