# Generated by Django 2.2.10 on 2020-05-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_auto_20200516_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictioncusto',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
    ]
