# Generated by Django 2.2.7 on 2020-02-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_character_victory_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fencing_league',
            field=models.BooleanField(default=False),
        ),
    ]
