# Generated by Django 2.2.7 on 2019-12-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_tourofdutyref_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
