# Generated by Django 2.0.2 on 2018-05-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_auto_20180512_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alliance',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='rid',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
