# Generated by Django 2.2.7 on 2020-04-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_auto_20200330_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('alliance', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('jumproutes', models.ManyToManyField(blank=True, null=True, to='collector.System')),
            ],
        ),
    ]
