# Generated by Django 2.2.7 on 2020-04-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='jumproutes',
            field=models.ManyToManyField(blank=True, null=True, related_name='_system_jumproutes_+', to='collector.System'),
        ),
    ]
