# Generated by Django 2.2.7 on 2019-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_auto_20191206_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
