# Generated by Django 2.2 on 2021-03-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_auto_20210328_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='alliance_hash',
        ),
    ]
