# Generated by Django 2.0.2 on 2018-05-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_auto_20180512_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges', models.PositiveIntegerField(blank=True, default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShieldRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=16)),
                ('protection_min', models.PositiveIntegerField(blank=True, default=10)),
                ('protection_max', models.PositiveIntegerField(blank=True, default=20)),
                ('hits', models.PositiveIntegerField(blank=True, default=10)),
                ('cost', models.PositiveIntegerField(blank=True, default=500)),
                ('is_compatible_with_medium_armor', models.BooleanField(default=False)),
                ('is_compatible_with_hard_armor', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='shield',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Character'),
        ),
        migrations.AddField(
            model_name='shield',
            name='shield_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.ShieldRef'),
        ),
    ]
