# Generated by Django 2.2.10 on 2020-05-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_beneficeafflictioncusto_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficeafflictionref',
            options={'ordering': ['reference', 'value'], 'verbose_name': 'References: Benefice/Affliction'},
        ),
        migrations.AlterModelOptions(
            name='blessingcurseref',
            options={'ordering': ['reference'], 'verbose_name': 'References: Blessing/Curse'},
        ),
    ]
