# Generated by Django 2.2.7 on 2020-02-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_character_fencing_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='watermark',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
