# Generated by Django 2.0.2 on 2018-05-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_auto_20180505_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='SK_TOTAL',
            field=models.IntegerField(default=0),
        ),
    ]
