# Generated by Django 2.0.2 on 2018-05-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_auto_20180513_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponref',
            name='cost',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
