# Generated by Django 2.2.10 on 2021-03-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_remove_character_alliance_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='caste',
            field=models.CharField(choices=[('Nobility', 'Nobility'), ('Church', 'Church'), ('Guild', 'Guild'), ('Alien', 'Alien'), ('Other', 'Other'), ('Freefolk', 'Freefolk'), ('Think Machine', 'Think Machine'), ('Caliphate (PO)', 'Kurgan (Planetary Origin)'), ('Caliphate (E)', 'Kurgan (Environment)'), ('Caliphate (U)', 'Kurgan (Usun)')], default='Other', max_length=20),
        ),
    ]
