# Generated by Django 2.0.2 on 2018-05-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_character_sk_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='PA_AGI',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_AWA',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_BOD',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_CON',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_INT',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_MOV',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_PRE',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_REF',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_STR',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_TEC',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_TEM',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_WIL',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
