# Generated by Django 2.2.10 on 2020-05-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0021_auto_20200522_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyberwareref',
            options={'verbose_name': 'References: Cyberware'},
        ),
        migrations.AlterModelOptions(
            name='loot',
            options={'verbose_name': 'Miscellaneous: Loot'},
        ),
        migrations.AlterModelOptions(
            name='ritualref',
            options={'ordering': ['category', 'reference', 'path', 'level'], 'verbose_name': 'References: Rituals'},
        ),
        migrations.AlterModelOptions(
            name='skillref',
            options={'ordering': ['is_speciality', 'is_wildcard', 'reference'], 'verbose_name': 'References: Skill'},
        ),
    ]
