# Generated by Django 2.2.7 on 2020-04-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0021_auto_20200406_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='jumproutes',
        ),
        migrations.AddField(
            model_name='system',
            name='jump_road_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.System'),
        ),
    ]
