# Generated by Django 2.2.7 on 2019-12-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0021_character_lifepath_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourofdutyref',
            options={'ordering': ['category', 'caste', 'topic', 'reference'], 'verbose_name': 'Tour of Duty Reference'},
        ),
    ]
