# Generated by Django 2.2.10 on 2020-05-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_auto_20200522_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyberfeature',
            options={'verbose_name': 'References: Cyberfeature'},
        ),
    ]
