# Generated by Django 2.0.2 on 2018-05-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_auto_20180513_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alliancehash',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
    ]
