# Generated by Django 2.2.7 on 2020-04-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_auto_20200406_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='full_name',
            new_name='name',
        ),
    ]
