# Generated by Django 2.2.7 on 2019-12-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_auto_20191208_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficeafflictionref',
            options={'ordering': ['reference', '-value']},
        ),
    ]
