# Generated by Django 2.2.10 on 2020-05-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0023_auto_20200522_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourofdutyref',
            options={'ordering': ['category', 'reference'], 'verbose_name': 'References: ToD'},
        ),
    ]
