# Generated by Django 2.2.7 on 2019-12-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0023_auto_20191208_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficeafflictionref',
            options={'ordering': ['reference', 'value']},
        ),
    ]
