# Generated by Django 2.2.7 on 2020-04-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0023_auto_20200406_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='sector',
            field=models.CharField(default='Empire', max_length=200),
        ),
    ]
