# Generated by Django 2.2.10 on 2021-03-29 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0024_auto_20210330_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='br_tod_name',
        ),
    ]
