# Generated by Django 2.2.10 on 2020-05-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0024_auto_20200522_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orbitalitem',
            options={'ordering': ['distance'], 'verbose_name': 'Jumpweb: Orbital Item'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['name'], 'verbose_name': 'Jumpweb: System'},
        ),
    ]
