# Generated by Django 2.2.7 on 2019-12-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0024_auto_20191208_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCusto',
            fields=[
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='collector.Character')),
                ('PA_STR', models.PositiveIntegerField(default=0)),
                ('PA_CON', models.PositiveIntegerField(default=0)),
                ('PA_BOD', models.PositiveIntegerField(default=0)),
                ('PA_MOV', models.PositiveIntegerField(default=0)),
                ('PA_INT', models.PositiveIntegerField(default=0)),
                ('PA_WIL', models.PositiveIntegerField(default=0)),
                ('PA_TEM', models.PositiveIntegerField(default=0)),
                ('PA_PRE', models.PositiveIntegerField(default=0)),
                ('PA_REF', models.PositiveIntegerField(default=0)),
                ('PA_TEC', models.PositiveIntegerField(default=0)),
                ('PA_AGI', models.PositiveIntegerField(default=0)),
                ('PA_AWA', models.PositiveIntegerField(default=0)),
                ('occult_level', models.PositiveIntegerField(default=0)),
                ('occult_darkside', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
