# Generated by Django 2.2.7 on 2020-04-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0025_auto_20200406_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='jump_road_to',
            field=models.ManyToManyField(blank=True, related_name='_system_jump_road_to_+', to='collector.System'),
        ),
    ]
