# Generated by Django 2.2.7 on 2019-12-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0025_charactercusto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('character_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.CharacterCusto')),
                ('skill_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.SkillRef')),
            ],
            options={
                'ordering': ['character_custo', 'skill_ref'],
            },
        ),
    ]
