# Generated by Django 2.0.2 on 2018-05-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0025_auto_20180515_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorref',
            name='cost',
            field=models.PositiveIntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='armorref',
            name='encumbrance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='category',
            field=models.CharField(blank=True, choices=[('Soft', 'Soft Armor'), ('Medium', 'Medium Armor'), ('Hard', 'Hard Armor')], default='Soft', max_length=6),
        ),
    ]
