# Generated by Django 2.2.7 on 2020-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0026_auto_20200406_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='jump_road_to',
        ),
        migrations.AddField(
            model_name='system',
            name='jumproads',
            field=models.ManyToManyField(blank=True, related_name='_system_jumproads_+', to='collector.System'),
        ),
    ]
