# Generated by Django 2.2.10 on 2020-05-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0026_auto_20200522_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specie',
            options={'ordering': ['species', 'race'], 'verbose_name': 'References: Specie'},
        ),
    ]
