# Generated by Django 2.0.2 on 2018-05-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0026_auto_20180516_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorref',
            name='encumbrance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
