# Generated by Django 2.2.7 on 2020-04-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0027_auto_20200406_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='jumproads',
        ),
        migrations.AddField(
            model_name='system',
            name='jumproad',
            field=models.ManyToManyField(blank=True, related_name='_system_jumproad_+', to='collector.System'),
        ),
    ]
