# Generated by Django 2.2.10 on 2020-05-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0027_auto_20200522_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loot',
            options={'verbose_name': 'References: Loot'},
        ),
    ]
