# Generated by Django 2.0.2 on 2018-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0027_auto_20180516_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillref',
            name='category',
            field=models.CharField(choices=[('no', 'Uncategorized'), ('co', 'Combat'), ('di', 'Diplomacy'), ('sp', 'Spirituality'), ('te', 'Technical')], default='un', max_length=2),
        ),
    ]
