# Generated by Django 2.2.7 on 2019-12-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0027_charactercusto_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercusto',
            name='AP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='OP',
            field=models.IntegerField(default=0),
        ),
    ]
