# Generated by Django 2.2.10 on 2021-03-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0028_auto_20210330_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='balance_AP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='balance_OP',
            field=models.IntegerField(default=0),
        ),
    ]
