# Generated by Django 2.2.10 on 2020-05-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0028_auto_20200522_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ritualref',
            options={'ordering': ['category', 'path', 'level', 'reference'], 'verbose_name': 'References: Ritual'},
        ),
    ]
