# Generated by Django 2.2.7 on 2019-12-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0028_auto_20191224_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercusto',
            name='summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
