# Generated by Django 2.2.10 on 2020-05-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0029_auto_20200522_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(-2, 'Minimal'), (-1, 'Light'), (0, 'Mild'), (1, 'Strong'), (2, 'Maximal')], default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='collector.Character')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='npc', to='collector.Character')),
            ],
            options={
                'ordering': ('player', 'level', 'reference'),
            },
        ),
    ]
