# Generated by Django 2.0.2 on 2018-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0029_character_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='category',
            field=models.CharField(choices=[('none', 'None'), ('villain', 'Bad guy'), ('hero', 'Good guy'), ('henchman', 'Henchman'), ('player', 'Player')], default='none', max_length=16),
        ),
    ]
