# Generated by Django 2.2.7 on 2020-04-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0029_auto_20200406_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['name']},
        ),
    ]
