# Generated by Django 2.2.10 on 2021-03-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0029_auto_20210330_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourofdutyref',
            options={'ordering': ['category', 'caste', 'reference'], 'verbose_name': 'FICS: ToD'},
        ),
        migrations.AddField(
            model_name='gear',
            name='power_consumption',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gear',
            name='power_storage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='gear',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
