# Generated by Django 2.2.7 on 2019-12-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0029_charactercusto_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlessingCurseCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blessing_curse_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.BlessingCurseRef')),
                ('character_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.CharacterCusto')),
            ],
            options={
                'ordering': ['character_custo', 'blessing_curse_ref'],
            },
        ),
        migrations.CreateModel(
            name='BeneficeAfflictionCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefice_affliction_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.BeneficeAfflictionRef')),
                ('character_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.CharacterCusto')),
            ],
            options={
                'ordering': ['character_custo', 'benefice_affliction_ref'],
            },
        ),
    ]
