# Generated by Django 2.2.10 on 2020-05-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0030_bloke'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictionmodificator',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
    ]
