# Generated by Django 2.0.2 on 2018-05-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0030_auto_20180517_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='AP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='OP',
            field=models.IntegerField(default=0),
        ),
    ]
