# Generated by Django 2.2.7 on 2020-04-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0030_auto_20200406_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
