# Generated by Django 2.2.7 on 2020-04-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0031_auto_20200406_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='color',
            field=models.CharField(default='#C0C0C0', max_length=16),
        ),
        migrations.AddField(
            model_name='system',
            name='dtj',
            field=models.FloatField(default=69),
        ),
        migrations.AddField(
            model_name='system',
            name='garrison',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='system',
            name='group',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='jump',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='tech',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='system',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
