# Generated by Django 2.2.10 on 2021-04-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0031_auto_20210330_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='weapon_of_choice',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
