# Generated by Django 2.0.2 on 2018-05-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0031_auto_20180527_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='AP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='OP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='attributes_list',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='talent',
            name='skills_list',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='talent',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
