# Generated by Django 2.2.10 on 2020-05-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0031_beneficeafflictionmodificator_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficeaffliction',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
