# Generated by Django 2.2.10 on 2021-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0032_weapon_weapon_of_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weaponref',
            options={'ordering': ['meta_type', 'category', 'reference', 'origins', 'damage_class'], 'verbose_name': 'FICS: Weapon'},
        ),
        migrations.AddField(
            model_name='weaponref',
            name='fusion_cell',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='caliber',
            field=models.CharField(blank=True, default='n/a', max_length=16),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='damage_class',
            field=models.CharField(default='1D6', max_length=16),
        ),
    ]
