# Generated by Django 2.2.7 on 2020-04-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0032_auto_20200406_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='discovered',
            field=models.BooleanField(default=True),
        ),
    ]
