# Generated by Django 2.2.10 on 2020-05-31 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0033_auto_20200531_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficeaffliction',
            name='value',
        ),
    ]
