# Generated by Django 2.0.2 on 2018-06-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0033_auto_20180528_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficeAfflictionRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('value', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('ba', 'Background'), ('co', 'Community'), ('po', 'Possessions'), ('ri', 'Riches'), ('st', 'Status'), ('ot', 'Other')], default='ot', max_length=2)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
