# Generated by Django 2.2.7 on 2020-04-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0033_system_discovered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
    ]
