# Generated by Django 2.2.10 on 2020-06-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0034_remove_beneficeaffliction_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='RitualCusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.CharacterCusto')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.RitualRef')),
            ],
        ),
    ]
