# Generated by Django 2.2.10 on 2021-04-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0034_auto_20210405_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorref',
            name='meta_type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
