# Generated by Django 2.0.2 on 2018-06-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0034_beneficeafflictionref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficeafflictionref',
            name='reference',
            field=models.CharField(max_length=64),
        ),
    ]
