# Generated by Django 2.2.7 on 2020-04-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0034_auto_20200408_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='discovery',
            field=models.IntegerField(default=5018),
        ),
        migrations.AlterField(
            model_name='system',
            name='color',
            field=models.CharField(default='#CCC', max_length=16),
        ),
    ]
