# Generated by Django 2.2.10 on 2020-06-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0035_ritualcusto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Character')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.RitualRef')),
            ],
        ),
    ]
