# Generated by Django 2.2.7 on 2020-04-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0035_auto_20200408_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='discovery',
            field=models.IntegerField(default=4994),
        ),
    ]
