# Generated by Django 2.2.10 on 2021-04-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0035_armorref_meta_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ritualref',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='ritualref',
            name='drawbacks',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='ritualref',
            name='modus_operandi',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='ritualref',
            name='range',
            field=models.CharField(choices=[('0', 'Touch'), ('1', 'Sight'), ('2', 'Sensory'), ('3', 'Distance'), ('4', 'Self')], default='tou', max_length=32),
        ),
    ]
