# Generated by Django 2.0.2 on 2018-06-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0036_auto_20180606_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shield',
            name='charges',
            field=models.PositiveIntegerField(blank=True, default=10),
        ),
    ]
