# Generated by Django 2.2.7 on 2020-04-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0036_auto_20200408_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='discovered',
        ),
    ]
