# Generated by Django 2.2.10 on 2021-04-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0036_auto_20210406_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ritualref',
            name='duration',
            field=models.CharField(choices=[('0', 'Instant'), ('1', 'Temporary'), ('2', 'Prolonged'), ('3', 'Perpetual')], default='ins', max_length=32),
        ),
    ]
