# Generated by Django 2.0.2 on 2018-06-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0037_auto_20180606_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='category',
            field=models.CharField(choices=[('none', 'None'), ('villain', 'Bad guy'), ('hero', 'Good guy'), ('henchman', 'Henchman'), ('player', 'Player'), ('support', 'Support'), ('auto', 'Autochton')], default='none', max_length=16),
        ),
    ]
