# Generated by Django 2.2.10 on 2021-04-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0037_auto_20210406_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritual',
            name='attribute_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ritual',
            name='skill_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ritual',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
