# Generated by Django 2.2.10 on 2021-04-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0038_auto_20210406_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='occult_fire_power',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
