# Generated by Django 2.2.7 on 2020-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0038_auto_20200408_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='symbol',
            field=models.CharField(default='9', max_length=1),
        ),
    ]
