# Generated by Django 2.0.2 on 2018-06-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0038_auto_20180611_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=64)),
                ('friends', models.TextField(blank=True, default='', max_length=128)),
                ('foes', models.TextField(blank=True, default='', max_length=128)),
                ('narrative', models.TextField(blank=True, default='', max_length=512)),
                ('resolution', models.TextField(blank=True, default='', max_length=512)),
            ],
        ),
    ]
