# Generated by Django 2.2.10 on 2020-06-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0038_auto_20200604_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ritualcusto',
            old_name='reference',
            new_name='ritual_ref',
        ),
    ]
