# Generated by Django 2.2.10 on 2020-04-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0039_system_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('ship_class', models.CharField(max_length=200)),
                ('ship_grade', models.CharField(max_length=200)),
                ('engines_type', models.CharField(max_length=200)),
                ('shields_type', models.CharField(max_length=200)),
                ('size_rating', models.PositiveIntegerField(default=1)),
                ('dim_length', models.PositiveIntegerField(default=1)),
                ('dim_width', models.PositiveIntegerField(default=1)),
                ('dim_height', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
