# Generated by Django 2.2.10 on 2020-06-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0039_auto_20200604_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ritual',
            old_name='reference',
            new_name='ritual_ref',
        ),
    ]
