# Generated by Django 2.2.10 on 2021-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0039_character_occult_fire_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ritual',
            name='skill_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
