# Generated by Django 2.0.2 on 2018-06-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0039_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='category',
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('standard', 'Standard'), ('villain', 'Villain'), ('player', 'Player'), ('boss', 'Boss'), ('support', 'Support'), ('nameless', 'Nameless')], default='standard', max_length=16),
        ),
    ]
