# Generated by Django 2.2.10 on 2021-09-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0040_auto_20210409_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='challenge',
            field=models.TextField(blank=True, default=''),
        ),
    ]
