# Generated by Django 2.0.2 on 2018-06-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0040_auto_20180616_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('standard', 'Standard'), ('villain', 'Villain'), ('player', 'Player'), ('boss', 'Boss'), ('grunt', 'Grunt'), ('support', 'Support'), ('nameless', 'Nameless')], default='standard', max_length=16),
        ),
    ]
