# Generated by Django 2.2.10 on 2020-06-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0040_auto_20200604_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('variant', models.CharField(max_length=128)),
                ('category', models.CharField(blank=True, choices=[('0', 'Miscellaneous'), ('1', 'Beverage/Food'), ('2', 'Medical Supplies'), ('3', 'Communications'), ('4', 'Tools'), ('5', 'Think Machines'), ('6', 'Drugs'), ('7', 'Clothing'), ('8', 'Vehicle'), ('9', 'Explosives')], default='Miscellaneous', max_length=32, null=True)),
                ('quality', models.CharField(blank=True, choices=[('0', 'Poor'), ('1', 'Standard'), ('2', 'High'), ('3', 'Premium'), ('4', 'Deluxe')], default='Standard', max_length=32, null=True)),
                ('availability', models.CharField(blank=True, choices=[('0', 'Exotic'), ('1', 'Rare'), ('2', 'Uncommon'), ('3', 'Common'), ('4', 'Very Common')], default='Common', max_length=32, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, choices=[('1', 'apiece'), ('x10', 'per 10'), ('x100', 'per 100'), ('x1000', 'per 1000'), ('litre', 'per litre'), ('m3', 'per cubic meter'), ('kg', 'per kg'), ('g', 'per g'), ('mg', 'per mg'), ('day', 'per day'), ('night', 'per night'), ('week', 'per week'), ('month', 'per month'), ('year', 'per year')], default='apiece', max_length=32, null=True)),
                ('origin', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('tech_level', models.PositiveIntegerField(default=4)),
                ('price', models.FloatField(default=0.0)),
                ('firebird_price', models.PositiveIntegerField(default=0)),
                ('wing_price', models.PositiveIntegerField(default=0)),
                ('crest_price', models.PositiveIntegerField(default=0)),
                ('talon_price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('reference', models.CharField(blank=True, choices=[('FS2CRB', 'Fading Suns 2ed Core Rulebook'), ('DEM', 'Introduced in epic Deus Ex Machina'), ('ANTU', 'Introduced in epic Abusus Non Tollit Usum'), ('MotJ', 'Merchants of the Jumpweb'), ('FL:T', 'Forbidden Lore: Technology'), ('AT', 'Arcane Tech'), ('FSC', 'Fading Suns Companion')], default='FS2CRB', max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'References: Gear',
            },
        ),
    ]
