# Generated by Django 2.2.7 on 2020-04-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0040_spacecraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='RitualRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('0', 'Psi'), ('1', 'Theurgy'), ('2', 'Symbiosis'), ('3', 'Runecasting')], max_length=32)),
                ('level', models.IntegerField(default=1)),
                ('attribute', models.CharField(default='PA_TEM', max_length=6)),
                ('range', models.CharField(blank=True, choices=[('0', 'Touch'), ('1', 'Sight')], default='tou', max_length=32)),
                ('duration', models.CharField(blank=True, choices=[('0', 'Instant'), ('1', 'Temporary'), ('2', 'Prolonged')], default='ins', max_length=32)),
                ('path', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('wyrd_cost', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.SkillRef')),
            ],
            options={
                'ordering': ['category', 'reference', 'path', 'level'],
            },
        ),
    ]
