# Generated by Django 2.2 on 2021-11-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0041_auto_20210929_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='archive_level',
            field=models.CharField(blank=True, choices=[('ARK', 'Archive'), ('WKS', 'Workshop'), ('NON', 'None')], default='NON', max_length=5),
        ),
    ]
