# Generated by Django 2.2.10 on 2020-06-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0041_gear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='variant',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
