# Generated by Django 2.2.7 on 2020-04-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0041_ritualref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritualref',
            name='gesture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ritualref',
            name='liturgy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ritualref',
            name='prayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ritualref',
            name='duration',
            field=models.CharField(blank=True, choices=[('0', 'Instant'), ('1', 'Temporary'), ('2', 'Prolonged'), ('2', 'Perpetual')], default='ins', max_length=32),
        ),
        migrations.AlterField(
            model_name='ritualref',
            name='range',
            field=models.CharField(blank=True, choices=[('0', 'Touch'), ('1', 'Sight'), ('2', 'Sensory'), ('3', 'Distance')], default='tou', max_length=32),
        ),
    ]
