# Generated by Django 2.0.2 on 2018-06-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0041_auto_20180616_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('mastermind', 'Mastermind'), ('villain', 'Villain'), ('boss', 'Boss'), ('player', 'Player'), ('standard', 'Standard'), ('thug', 'Thug'), ('grunt', 'Grunt'), ('support', 'Support'), ('nameless', 'Nameless')], default='standard', max_length=16),
        ),
    ]
