# Generated by Django 2.2.10 on 2020-06-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0042_auto_20200623_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='magna_carta_entry',
            field=models.CharField(blank=True, choices=[('0', 'legit'), ('1', 'Restricted Sell'), ('2', 'Restricted Usage'), ('3', 'Unauthorized'), ('4', 'Proscribed by the Church')], default='0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='quality',
            field=models.CharField(choices=[('0', 'Poor'), ('1', 'Standard'), ('2', 'High'), ('3', 'Premium'), ('4', 'Deluxe')], default='Standard', max_length=32),
        ),
        migrations.AlterField(
            model_name='gear',
            name='unit',
            field=models.CharField(blank=True, choices=[('1', 'apiece'), ('x10', 'per 10'), ('x100', 'per 100'), ('x1000', 'per 1000'), ('litre', 'per litre'), ('m3', 'per cubic meter'), ('kg', 'per kg'), ('g', 'per g'), ('mg', 'per mg'), ('day', 'per day'), ('night', 'per night'), ('week', 'per week'), ('month', 'per month'), ('year', 'per year'), ('2', 'pair')], default='apiece', max_length=32, null=True),
        ),
    ]
