# Generated by Django 2.2.7 on 2020-04-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0042_auto_20200415_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritualref',
            name='modus_operandi',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
