# Generated by Django 2.0.2 on 2018-06-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0043_auto_20180616_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='profile',
            field=models.CharField(choices=[('combat', 'Combat'), ('physical', 'Physical'), ('spiritual', 'Spiritual'), ('standard', 'Standard')], default='standard', max_length=16),
        ),
    ]
