# Generated by Django 2.2.7 on 2020-04-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0043_ritualref_modus_operandi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritualref',
            name='drawbacks',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
