# Generated by Django 2.2.10 on 2020-06-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0043_auto_20200623_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'Miscellaneous'), ('1', 'Beverage/Food'), ('2', 'Medical Supplies'), ('3', 'Communications'), ('4', 'Tools'), ('5', 'Think Machines'), ('6', 'Drugs'), ('7', 'Clothing'), ('8', 'Vehicle'), ('9', 'Explosives'), ('10', 'Entertainment')], default='Miscellaneous', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='magna_carta_entry',
            field=models.CharField(blank=True, choices=[('0', 'Legit'), ('1', 'Restricted Sell'), ('2', 'Restricted Usage'), ('3', 'Unauthorized'), ('4', 'Proscribed by the Church')], default='0', max_length=32, null=True),
        ),
    ]
