# Generated by Django 2.2.10 on 2020-06-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0044_auto_20200625_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='unit',
            field=models.CharField(blank=True, choices=[('1', 'piece'), ('x10', 'x10 pieces'), ('x100', 'x100 pieces'), ('x1000', 'x1000 pieces'), ('litre', 'litre'), ('m3', 'cubic meter'), ('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('day', 'day'), ('night', 'night'), ('week', 'week'), ('month', 'month'), ('year', 'year'), ('2', 'pair')], default='apiece', max_length=32, null=True),
        ),
    ]
