# Generated by Django 2.2.7 on 2020-04-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0044_ritualref_drawbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='historical_figure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='nameless',
            field=models.BooleanField(default=False),
        ),
    ]
