# Generated by Django 2.2.10 on 2020-06-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0045_auto_20200625_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'Miscellaneous'), ('1', 'Beverage/Food'), ('2', 'Medical Supplies'), ('3', 'Communications'), ('4', 'Tools'), ('5', 'Think Machines'), ('6', 'Drugs'), ('7', 'Clothing'), ('8', 'Vehicle'), ('9', 'Explosives'), ('10', 'Entertainment'), ('11', 'Weapons'), ('12', 'Armors'), ('13', 'Resources')], default='Miscellaneous', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='reference',
            field=models.CharField(blank=True, choices=[('FS2CRB', 'Fading Suns 2ed Core Rulebook'), ('DEM', 'Introduced in epic Deus Ex Machina'), ('ANTU', 'Introduced in epic Abusus Non Tollit Usum'), ('MotJ', 'Merchants of the Jumpweb'), ('FL:T', 'Forbidden Lore: Technology'), ('AT', 'Arcane Tech'), ('FSC', 'Fading Suns Companion')], default='MotJ', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='unit',
            field=models.CharField(blank=True, choices=[('1', 'piece'), ('x10', 'x10 pieces'), ('x100', 'x100 pieces'), ('x1000', 'x1000 pieces'), ('litre', 'litre'), ('m3', 'cubic meter'), ('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('day', 'day'), ('night', 'night'), ('week', 'week'), ('month', 'month'), ('year', 'year'), ('2', 'pair'), ('metric ton', 'metric ton')], default='apiece', max_length=32, null=True),
        ),
    ]
