# Generated by Django 2.0.2 on 2018-06-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0045_auto_20180616_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.CharField(choices=[('combat', 'Combat'), ('physical', 'Physical'), ('spiritual', 'Spiritual'), ('standard', 'Standard'), ('courtisan', 'Courtisan'), ('scholar', 'Scholar'), ('adventurer', 'Adventurer')], default='standard', max_length=16),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('mastermind', 'Mastermind'), ('villain', 'Villain'), ('boss', 'Boss'), ('player', 'Player'), ('henchman', 'Henchman'), ('brute', 'Brute'), ('standard', 'Standard'), ('nameless', 'Nameless')], default='standard', max_length=16),
        ),
    ]
