# Generated by Django 2.0.2 on 2018-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0046_auto_20180616_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.CharField(choices=[('tech', 'Tech'), ('physical', 'Physical'), ('spiritual', 'Spiritual'), ('standard', 'Standard'), ('courtisan', 'Courtisan'), ('scholar', 'Scholar'), ('guilder', 'Guilder')], default='standard', max_length=16),
        ),
    ]
