# Generated by Django 2.2.10 on 2020-04-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0046_auto_20200415_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='buildlog',
            field=models.TextField(blank=True, default=''),
        ),
    ]
