# Generated by Django 2.2.10 on 2020-06-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0046_auto_20200628_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'Miscellaneous'), ('1', 'Beverage/Food'), ('2', 'Medical Supplies'), ('3', 'Communications'), ('4', 'Tools'), ('5', 'Think Machines'), ('6', 'Drugs'), ('7', 'Clothing'), ('8', 'Vehicle'), ('9', 'Explosives'), ('10', 'Entertainment'), ('11', 'Weapons'), ('12', 'Armors'), ('13', 'Resources'), ('14', 'Services')], default='Miscellaneous', max_length=32, null=True),
        ),
    ]
