# Generated by Django 2.2.10 on 2020-04-29 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0047_character_buildlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberwareRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64)),
                ('replacement_for', models.CharField(max_length=64)),
                ('value', models.IntegerField(default=0)),
                ('intolerance', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Cyberware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Character')),
                ('cyberware_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.CyberwareRef')),
            ],
        ),
        migrations.CreateModel(
            name='Cyberfeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64)),
                ('value', models.IntegerField(default=1)),
                ('description', models.TextField(default='', max_length=1024)),
                ('cyberware_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.CyberwareRef')),
            ],
        ),
    ]
