# Generated by Django 2.2.10 on 2020-04-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0048_cyberfeature_cyberware_cyberwareref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyberfeature',
            name='cyberware_ref',
        ),
        migrations.AddField(
            model_name='cyberwareref',
            name='cyberfeatures',
            field=models.ManyToManyField(to='collector.Cyberfeature'),
        ),
    ]
