# Generated by Django 2.2.10 on 2020-06-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0048_auto_20200628_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponref',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
