# Generated by Django 2.0.2 on 2018-06-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0048_auto_20180616_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('08mastermind', 'Legend'), ('07villain', 'Champion'), ('06boss', 'Elite'), ('05player', 'Veteran'), ('04henchman', 'Seasoned'), ('03brute', 'Advanced'), ('02standard', 'Standard'), ('01nameless', 'Nameless')], default='standard', max_length=16),
        ),
    ]
