# Generated by Django 2.0.2 on 2018-06-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0049_auto_20180616_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('08', 'Legend'), ('07', 'Champion'), ('06', 'Elite'), ('05', 'Veteran'), ('04', 'Seasoned'), ('03', 'Superior'), ('02', 'Standard'), ('01', 'Inferior')], default='standard', max_length=16),
        ),
    ]
