# Generated by Django 2.2.10 on 2020-06-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0049_weaponref_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponref',
            name='category',
            field=models.CharField(blank=True, choices=[('MELEE', 'Melee weapon'), ('P', 'Pistol/revolver'), ('RIF', 'Rifle'), ('SMG', 'Submachinegun'), ('SHG', 'Shotgun'), ('HVY', 'Heavy weapon'), ('EX', 'Exotic weapon'), ('SP', 'Special')], default='RIF', max_length=5),
        ),
    ]
