# Generated by Django 2.2.10 on 2020-04-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0049_auto_20200429_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberfeature',
            name='complexity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cyberfeature',
            name='intolerance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cyberfeature',
            name='tech_level',
            field=models.IntegerField(default=5),
        ),
    ]
