# Generated by Django 2.2.10 on 2020-04-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0050_auto_20200429_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberfeature',
            name='category',
            field=models.CharField(blank=True, choices=[('0', 'Trait'), ('1', 'Attachment'), ('2', 'Power Source'), ('3', 'Look'), ('4', 'Material'), ('5', 'Quality'), ('6', 'Technology')], default='Trait', max_length=20),
        ),
    ]
