# Generated by Django 2.2.10 on 2020-07-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0050_auto_20200628_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponref',
            name='tech_level',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
    ]
