# Generated by Django 2.0.2 on 2018-06-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0051_auto_20180616_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='stars',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
