# Generated by Django 2.2.10 on 2020-07-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0051_weaponref_tech_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orbitalitem',
            options={'ordering': ['system', 'distance'], 'verbose_name': 'Jumpweb: Orbital Item'},
        ),
    ]
