# Generated by Django 2.2.10 on 2020-04-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0051_cyberfeature_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberfeature',
            name='value_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cyberfeature',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='cyberwareref',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
