# Generated by Django 2.0.6 on 2018-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0052_character_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficeafflictionref',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
