# Generated by Django 2.2.10 on 2020-04-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0052_auto_20200430_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyberfeature',
            options={'verbose_name': 'Cyberfeature'},
        ),
        migrations.AlterModelOptions(
            name='cyberwareref',
            options={'verbose_name': 'Cyberware Reference'},
        ),
        migrations.AddField(
            model_name='cyberwareref',
            name='tech_level',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
