# Generated by Django 2.2.10 on 2020-07-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0052_auto_20200716_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.CharField(blank=True, default='https://drive.google.com/open?id=15hdubdMt1t_deSXkbg9dsAjWi5tZwMU0', max_length=512),
        ),
    ]
