# Generated by Django 2.2.10 on 2020-04-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0053_auto_20200430_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberwareref',
            name='tech_level',
            field=models.IntegerField(default=0),
        ),
    ]
