# Generated by Django 2.2.10 on 2020-07-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0053_auto_20200725_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.CharField(blank=True, default='https://drive.google.com/open?id=15hdubdMt1t_deSXkbg9dsAjWi5tZwMU0', max_length=1024),
        ),
    ]
