# Generated by Django 2.2.10 on 2020-04-30 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0054_auto_20200430_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cyberfeature',
            old_name='intolerance',
            new_name='incompatibility',
        ),
        migrations.RenameField(
            model_name='cyberwareref',
            old_name='intolerance',
            new_name='incompatibility',
        ),
    ]
