# Generated by Django 2.2.10 on 2020-04-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0055_auto_20200430_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberwareref',
            name='cyberfeatures',
            field=models.ManyToManyField(blank=True, to='collector.Cyberfeature'),
        ),
    ]
