# Generated by Django 2.2 on 2021-11-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0055_auto_20211103_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='archive_level',
            field=models.CharField(blank=True, choices=[('ARK', 'Archive'), ('WKS', 'Workshop'), ('NON', 'None')], default='NON', max_length=5),
        ),
    ]
