# Generated by Django 2.0.6 on 2018-08-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0056_beneficeaffliction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficeaffliction',
            name='ba_ref',
        ),
        migrations.RemoveField(
            model_name='beneficeaffliction',
            name='character',
        ),
        migrations.DeleteModel(
            name='BeneficeAffliction',
        ),
    ]
