# Generated by Django 2.2.10 on 2020-04-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0056_auto_20200430_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyberwareref',
            name='replacement_for',
        ),
        migrations.AddField(
            model_name='cyberware',
            name='replacement_for',
            field=models.CharField(default='add on', max_length=64),
        ),
    ]
