# Generated by Django 2.2 on 2020-10-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0056_character_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='stories_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
