# Generated by Django 2.2 on 2020-10-04 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0057_character_stories_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='alliancehash',
            new_name='alliance_hash',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='buildlog',
            new_name='build_log',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='lifepath_total',
            new_name='life_path_total',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='onsave_reroll_attributes',
            new_name='on_save_re_roll_attributes',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='onsave_reroll_skills',
            new_name='on_save_re_roll_skills',
        ),
    ]
