# Generated by Django 2.2.10 on 2020-04-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0057_auto_20200430_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberware',
            name='replacement_for',
            field=models.CharField(default='Add on', max_length=64),
        ),
    ]
