# Generated by Django 2.0 on 2018-09-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0057_auto_20180806_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.CharField(choices=[('tech', 'Tech'), ('physical', 'Physical'), ('spiritual', 'Spiritual'), ('standard', 'Standard'), ('courtisan', 'Courtisan'), ('scholar', 'Scholar'), ('guilder', 'Guilder'), ('undefined', 'Undefined')], default='undefined', max_length=16),
        ),
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(choices=[('08', 'Legend'), ('07', 'Champion'), ('06', 'Elite'), ('05', 'Veteran'), ('04', 'Seasoned'), ('03', 'Superior'), ('02', 'Standard'), ('01', 'Inferior'), ('00', 'Undefined')], default='00', max_length=16),
        ),
    ]
