# Generated by Django 2.0 on 2018-11-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0058_auto_20180918_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.IntegerField(blank=True, default=5017)),
                ('population_count', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(blank=True, default='', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=128)),
                ('is_public', models.BooleanField(default=True)),
                ('is_editable', models.BooleanField(default=True)),
            ],
        ),
    ]
