# Generated by Django 2.2 on 2020-10-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0058_auto_20201004_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
