# Generated by Django 2.2.10 on 2020-04-30 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0058_auto_20200430_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['full_name']},
        ),
    ]
