# Generated by Django 2.2 on 2020-10-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0059_tourofdutyref_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourofdutyref',
            old_name='error',
            new_name='valid',
        ),
    ]
