# Generated by Django 2.2.10 on 2020-04-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0059_auto_20200430_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberwareref',
            name='surgery_cost',
            field=models.IntegerField(default=0),
        ),
    ]
