# Generated by Django 2.2.10 on 2020-04-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0060_cyberwareref_surgery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberwareref',
            name='complexity',
            field=models.IntegerField(default=0),
        ),
    ]
