# Generated by Django 2.0 on 2018-11-24 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0060_auto_20181124_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.Epic'),
        ),
    ]
