# Generated by Django 2.2 on 2020-10-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0003_auto_20200327_2056'),
        ('collector', '0062_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='main_epic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarist.Epic'),
        ),
    ]
