# Generated by Django 2.2 on 2020-10-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0063_profile_main_epic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['main_epic', '-main_character']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.Character'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarist.Epic'),
        ),
    ]
