# Generated by Django 2.2 on 2020-10-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0064_auto_20201017_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='need_fix',
            field=models.BooleanField(default=False),
        ),
    ]
