# Generated by Django 2.0 on 2018-11-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0064_auto_20181125_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=128)),
                ('gamemaster', models.CharField(blank=True, default='zaffarelli@gmail.com', max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.Act')),
                ('drama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.Drama')),
                ('epic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.Epic')),
            ],
            options={
                'ordering': ['title', 'epic'],
            },
        ),
    ]
