# Generated by Django 2.0 on 2018-11-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0066_auto_20181126_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficeafflictionref',
            options={'ordering': ['reference']},
        ),
        migrations.AddField(
            model_name='character',
            name='BA_TOTAL',
            field=models.IntegerField(default=0),
        ),
    ]
