# Generated by Django 2.0 on 2018-11-26 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0067_auto_20181126_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficeAffliction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('beneficeaffliction_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.BeneficeAfflictionRef')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Character')),
            ],
            options={
                'ordering': ['beneficeaffliction_ref'],
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['skill_ref']},
        ),
    ]
