# Generated by Django 2.0 on 2018-11-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0068_auto_20181126_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeaffliction',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
    ]
