# Generated by Django 2.2 on 2020-11-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0068_auto_20201103_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloke',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
