# Generated by Django 2.2 on 2021-11-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0068_auto_20211107_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='archive_level',
            field=models.CharField(blank=True, choices=[('WKS', 'Workshop'), ('NON', 'None'), ('ARK', 'Archive')], default='NON', max_length=5),
        ),
    ]
