# Generated by Django 2.2 on 2020-11-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0069_bloke_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloke',
            options={'ordering': ['character', 'level', 'npc']},
        ),
        migrations.RemoveField(
            model_name='bloke',
            name='pc',
        ),
        migrations.AddField(
            model_name='bloke',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='collector.Character'),
        ),
    ]
