# Generated by Django 2.2 on 2020-11-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0070_auto_20201103_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.TextField(default='', max_length=256),
        ),
    ]
