# Generated by Django 2.1 on 2018-12-06 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0071_skillref_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillref',
            options={'ordering': ['group', 'reference']},
        ),
    ]
