# Generated by Django 2.2 on 2020-11-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0071_character_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
    ]
