# Generated by Django 2.2 on 2020-11-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0072_auto_20201106_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='stories',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
