# Generated by Django 2.2 on 2021-11-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0072_auto_20211108_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='archive_level',
            field=models.CharField(blank=True, choices=[('ARK', 'Archive'), ('NON', 'None'), ('WKS', 'Workshop')], default='NON', max_length=5),
        ),
    ]
