# Generated by Django 2.1 on 2018-12-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0072_auto_20181206_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='smart_code',
            field=models.CharField(blank=True, default='xxxxxx', max_length=6),
        ),
    ]
