# Generated by Django 2.2 on 2021-11-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0073_auto_20211111_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='archive_level',
            field=models.CharField(blank=True, choices=[('NON', 'None'), ('WKS', 'Workshop'), ('ARK', 'Archive')], default='NON', max_length=5),
        ),
        migrations.AlterField(
            model_name='character',
            name='archive_level',
            field=models.CharField(blank=True, choices=[('NON', 'None'), ('WKS', 'Workshop'), ('ARK', 'Archive')], default='NON', max_length=5),
        ),
    ]
