# Generated by Django 2.1 on 2018-12-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0074_auto_20181207_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='chapter',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='drama',
            name='date',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='drama',
            name='place',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
