# Generated by Django 2.2 on 2021-11-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0074_auto_20211111_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorref',
            name='meta_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
