# Generated by Django 2.2 on 2020-11-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0075_auto_20201111_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitalitem',
            name='color',
            field=models.CharField(default='#FFF', max_length=20),
        ),
        migrations.AddField(
            model_name='orbitalitem',
            name='speed',
            field=models.FloatField(default=1.0),
        ),
    ]
