# Generated by Django 2.2 on 2021-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0075_auto_20211113_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceref',
            name='common_occult_pathes',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
