# Generated by Django 2.1 on 2018-12-09 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0075_auto_20181209_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drama',
            options={'ordering': ['epic', 'chapter', 'date', 'title']},
        ),
    ]
