# Generated by Django 2.2 on 2020-11-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0076_auto_20201111_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitalitem',
            name='azimut',
            field=models.FloatField(default=0),
        ),
    ]
