# Generated by Django 2.2 on 2021-11-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0076_allianceref_common_occult_pathes'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='known_systems',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
