# Generated by Django 2.1 on 2018-12-10 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0077_auto_20181209_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='drama',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='epic',
        ),
        migrations.AlterField(
            model_name='character',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarist.Act'),
        ),
        migrations.AlterField(
            model_name='character',
            name='drama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarist.Drama'),
        ),
        migrations.AlterField(
            model_name='character',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarist.Epic'),
        ),
        migrations.AlterField(
            model_name='config',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarist.Act'),
        ),
        migrations.AlterField(
            model_name='config',
            name='drama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarist.Drama'),
        ),
        migrations.AlterField(
            model_name='config',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarist.Epic'),
        ),
        migrations.DeleteModel(
            name='Act',
        ),
        migrations.DeleteModel(
            name='Drama',
        ),
        migrations.DeleteModel(
            name='Epic',
        ),
    ]
