# Generated by Django 2.2 on 2020-11-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0077_orbitalitem_azimut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbitalitem',
            name='category',
            field=models.CharField(choices=[('0', 'Sun'), ('1', 'Gas Giant'), ('2', 'Telluric'), ('3', 'Asteroids Belt'), ('4', 'Space Station'), ('5', 'Jumpgate'), ('6', 'Allied Forces'), ('7', 'Hostiles')], default='Telluric', max_length=20),
        ),
    ]
