# Generated by Django 2.2 on 2021-12-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0078_character_stigma'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='custo_descs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
