# Generated by Django 2.2 on 2020-11-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0078_auto_20201112_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='zoom_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='zoom_val',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
