# Generated by Django 2.1 on 2018-12-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0078_auto_20181210_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='stars',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
