# Generated by Django 2.2 on 2020-11-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0079_auto_20201115_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbitalitem',
            name='rings',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
