# Generated by Django 2.2 on 2021-12-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0079_character_custo_descs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='option_display_as_list',
            field=models.BooleanField(default=False),
        ),
    ]
