# Generated by Django 2.1 on 2019-01-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0080_auto_20181210_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillref',
            name='category',
            field=models.CharField(choices=[('no', 'Uncategorized'), ('co', 'Combat'), ('di', 'Diplomacy'), ('sp', 'Spirituality'), ('te', 'Technical'), ('ac', 'Action')], default='un', max_length=2),
        ),
    ]
