# Generated by Django 2.2 on 2021-12-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0080_profile_option_display_as_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
