# Generated by Django 2.2 on 2020-11-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0081_auto_20201115_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='overhead',
            field=models.IntegerField(default=0),
        ),
    ]
