# Generated by Django 2.2 on 2021-12-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0081_specie_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='vernacular',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
