# Generated by Django 2.1 on 2019-01-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0082_auto_20190110_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='build_log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
