# Generated by Django 2.2 on 2020-11-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0082_character_overhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
