# Generated by Django 2.2 on 2021-12-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0083_profile_option_display_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='audit',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
