# Generated by Django 2.1 on 2019-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0083_character_build_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='new_role', max_length=64, unique=True)),
                ('weights', models.CharField(default='[1,1,1,1,1,1,1,1,1,1,1,1]', max_length=128)),
                ('groups', models.CharField(default='[]', max_length=128)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='new_role', max_length=64, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('primaries', models.PositiveIntegerField(default=0)),
                ('maxi', models.PositiveIntegerField(default=10)),
                ('skills', models.PositiveIntegerField(default=0)),
                ('talents', models.PositiveIntegerField(default=0)),
                ('ba', models.PositiveIntegerField(default=0)),
                ('bc', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
    ]
