# Generated by Django 2.2 on 2020-12-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0083_character_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='rpg_system',
            field=models.CharField(choices=[('0', 'Undefined'), ('1', 'Fading Suns 2nd Edition'), ('2', 'Fading Suns FICS'), ('3', 'Pathfinder'), ('4', 'World of Darkness'), ('5', 'Call of Cthulhu 7E'), ('6', 'Polaris')], default='2', max_length=32),
        ),
    ]
