# Generated by Django 2.2 on 2020-12-22 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0084_config_rpg_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('rid', models.CharField(default='none', max_length=200)),
                ('birthdate', models.IntegerField(default=0)),
                ('gender', models.CharField(default='female', max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('player', models.CharField(blank=True, default='', max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date published')),
                ('nationality', models.CharField(default='American', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
