# Generated by Django 2.1 on 2019-02-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0084_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='act',
        ),
        migrations.RemoveField(
            model_name='character',
            name='drama',
        ),
    ]
