# Generated by Django 2.2 on 2021-12-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0084_character_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='audit',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
