# Generated by Django 2.2 on 2021-12-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0085_investigator_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='investigator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
