# Generated by Django 2.2 on 2021-12-27 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0086_auto_20211227_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='image',
        ),
    ]
