# Generated by Django 2.2 on 2020-12-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0086_auto_20201222_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='C_TOTAL',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='C_APP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='C_CHANCE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='C_CON',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='C_DEX',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='C_EDU',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='C_FOR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='C_INT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='C_POU',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='C_SANTE_MENTALE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='C_TAI',
            field=models.IntegerField(default=0),
        ),
    ]
