# Generated by Django 2.2 on 2020-12-23 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0087_auto_20201222_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talent',
        ),
        migrations.DeleteModel(
            name='TalentRef',
        ),
    ]
