# Generated by Django 2.2 on 2021-12-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0087_auto_20211227_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='on_save_re_roll_attributes',
        ),
        migrations.RemoveField(
            model_name='character',
            name='on_save_re_roll_skills',
        ),
    ]
