# Generated by Django 2.2 on 2021-12-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0088_auto_20211227_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='use_only_entrance',
        ),
    ]
