# Generated by Django 2.2 on 2021-12-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0089_remove_character_use_only_entrance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='is_partial',
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='is_partial',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='is_public',
        ),
    ]
