# Generated by Django 2.2 on 2020-12-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0090_remove_config_gamemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpgSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=32, unique=True)),
                ('game_mechanics', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'verbose_name': 'References: RPG system',
                'ordering': ['name', 'game_mechanics'],
            },
        ),
    ]
