# Generated by Django 2.2 on 2021-12-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0090_auto_20211227_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='wealth',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
