# Generated by Django 2.2 on 2021-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0091_character_wealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='cash_value',
            field=models.BooleanField(default=False),
        ),
    ]
