# Generated by Django 2.2 on 2020-12-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0092_auto_20201229_0243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['full_name'], 'verbose_name': 'FICS: Character'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['main_epic', '-main_character'], 'verbose_name': 'References: User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='ritualref',
            options={'ordering': ['category', 'path', 'level', 'reference'], 'verbose_name': 'FICS: Ritual'},
        ),
        migrations.AlterModelOptions(
            name='shieldref',
            options={'ordering': ['cost', 'reference'], 'verbose_name': 'FICS: Shield'},
        ),
        migrations.AlterModelOptions(
            name='shipsystem',
            options={'verbose_name': 'FICS: Ship System'},
        ),
        migrations.AlterModelOptions(
            name='skillref',
            options={'ordering': ['is_speciality', 'is_wildcard', 'reference'], 'verbose_name': 'FICS: Skill'},
        ),
        migrations.AlterModelOptions(
            name='tourofdutyref',
            options={'ordering': ['category', 'reference'], 'verbose_name': 'FICS: ToD'},
        ),
    ]
