# Generated by Django 2.2 on 2021-12-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0092_beneficeafflictionref_cash_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorref',
            name='he_sp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armorref',
            name='sa_sp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='armorref',
            name='sl_sp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armorref',
            name='to_sp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='armorref',
            name='wa_sp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='armorref',
            name='wl_sp',
            field=models.IntegerField(default=0),
        ),
    ]
