# Generated by Django 2.2 on 2021-12-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0094_auto_20211231_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorref',
            name='material_plastic',
            field=models.BooleanField(default=False),
        ),
    ]
