# Generated by Django 2.2 on 2020-12-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0094_auto_20201229_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['title', 'epic'], 'verbose_name': 'References: Campaign Config'},
        ),
        migrations.AlterModelOptions(
            name='investigator',
            options={'verbose_name': 'EDGE_7E: Investigator'},
        ),
    ]
