# Generated by Django 2.2 on 2020-12-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0095_auto_20201229_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyberfeature',
            options={'verbose_name': 'FICS: Cyberfeature'},
        ),
        migrations.AlterModelOptions(
            name='loot',
            options={'verbose_name': 'FICS: Loot'},
        ),
        migrations.AlterModelOptions(
            name='weaponref',
            options={'ordering': ['origins', 'reference', 'category', 'damage_class'], 'verbose_name': 'FICS: Weapon'},
        ),
    ]
