# Generated by Django 2.2 on 2020-12-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0096_auto_20201229_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyberwareref',
            options={'verbose_name': 'FICS: Cyberware'},
        ),
        migrations.AlterModelOptions(
            name='gear',
            options={'verbose_name': 'FICS: Gear'},
        ),
    ]
