# Generated by Django 2.2 on 2021-12-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0096_armorref_obstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorref',
            name='material_void',
            field=models.BooleanField(default=False),
        ),
    ]
