# Generated by Django 2.2 on 2020-12-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0097_auto_20201229_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specie',
            options={'ordering': ['species', 'race'], 'verbose_name': 'FICS: Specie'},
        ),
        migrations.AddField(
            model_name='rpgsystem',
            name='smart_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
