# Generated by Django 2.2 on 2021-12-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0097_armorref_material_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorref',
            name='material_ceramsteel',
            field=models.BooleanField(default=False, verbose_name='CE'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='encumbrance',
            field=models.PositiveIntegerField(default=0, verbose_name='ENC'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='he_sp',
            field=models.IntegerField(default=0, verbose_name='HE'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='material_connected',
            field=models.BooleanField(default=False, verbose_name='CO'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='material_fabric',
            field=models.BooleanField(default=False, verbose_name='FA'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='material_light',
            field=models.BooleanField(default=False, verbose_name='LI'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='material_metal',
            field=models.BooleanField(default=False, verbose_name='ME'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='material_plastic',
            field=models.BooleanField(default=False, verbose_name='PL'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='material_powered',
            field=models.BooleanField(default=False, verbose_name='PO'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='material_reinforced',
            field=models.BooleanField(default=False, verbose_name='RE'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='material_synth',
            field=models.BooleanField(default=False, verbose_name='SY'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='material_void',
            field=models.BooleanField(default=False, verbose_name='VO'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='obstruction',
            field=models.PositiveIntegerField(default=0, verbose_name='OBS'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='sa_sp',
            field=models.IntegerField(default=0, verbose_name='SA'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='sl_sp',
            field=models.IntegerField(default=0, verbose_name='SL'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='tech_level',
            field=models.PositiveIntegerField(default=3, verbose_name='TL'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='to_sp',
            field=models.IntegerField(default=0, verbose_name='TO'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='wa_sp',
            field=models.IntegerField(default=0, verbose_name='WA'),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='wl_sp',
            field=models.IntegerField(default=0, verbose_name='WL'),
        ),
    ]
