# Generated by Django 2.2 on 2021-12-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0098_auto_20211231_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorref',
            name='material_leather',
            field=models.BooleanField(default=False, verbose_name='LE'),
        ),
    ]
