# Generated by Django 2.2 on 2020-12-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0099_auto_20201229_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='rpgsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.RpgSystem'),
        ),
    ]
