# Generated by Django 2.2 on 2022-01-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0099_armorref_material_leather'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcusto',
            options={'ordering': ['character_custo', 'skill_ref__linked_to']},
        ),
    ]
