# Generated by Django 2.2 on 2022-01-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0100_auto_20220101_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='known_systems',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
