# Generated by Django 2.2 on 2020-12-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0100_config_rpgsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='logo',
            field=models.CharField(default='nologo.png', max_length=128),
        ),
    ]
