# Generated by Django 2.2 on 2022-01-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0101_auto_20220115_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='selected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
