# Generated by Django 2.2 on 2022-01-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0102_character_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='cast_figure',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
