# Generated by Django 2.2 on 2020-12-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0102_auto_20201230_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='back',
            field=models.CharField(default='back.png', max_length=128),
        ),
    ]
