# Generated by Django 2.2 on 2022-01-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0103_character_cast_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='xp_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='xp_spent',
            field=models.IntegerField(default=0),
        ),
    ]
