# Generated by Django 2.2 on 2022-01-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0104_auto_20220130_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritual',
            name='attribute_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ritual',
            name='skill_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
