# Generated by Django 2.2 on 2020-12-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0104_auto_20201231_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
