# Generated by Django 2.2 on 2020-12-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0105_campaign_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='height',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='investigator',
            name='weight',
            field=models.IntegerField(default=50),
        ),
    ]
