# Generated by Django 2.2 on 2022-02-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0105_auto_20220130_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=64, unique=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('data', models.TextField(blank=True, default='', max_length=4096)),
            ],
            options={
                'verbose_name': 'FICS: Sequence',
                'ordering': ['reference'],
            },
        ),
    ]
