# Generated by Django 2.2 on 2020-12-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0106_auto_20201231_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='entrance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investigator',
            name='importance',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='investigator',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigator',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigator',
            name='is_partial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investigator',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigator',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investigator',
            name='keyword',
            field=models.CharField(blank=True, default='new', max_length=32),
        ),
        migrations.AddField(
            model_name='investigator',
            name='narrative',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='investigator',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigator',
            name='spotlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigator',
            name='stars',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
