# Generated by Django 2.2 on 2022-02-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0106_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='incognito',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
