# Generated by Django 2.2 on 2022-05-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0107_character_incognito'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='azurites',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='diamonds',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='rubies',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
