# Generated by Django 2.2 on 2022-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0108_auto_20220519_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillref',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
