# Generated by Django 2.2 on 2021-01-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarist', '0023_auto_20201231_1735'),
        ('collector', '0108_auto_20210102_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarist.Epic'),
        ),
    ]
