# Generated by Django 2.2 on 2022-05-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0109_skillref_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
