# Generated by Django 2.2 on 2021-01-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0110_coc7skill_coc7skillref'),
    ]

    operations = [
        migrations.AddField(
            model_name='coc7skillref',
            name='category',
            field=models.CharField(choices=[('N/A', 'Aucune'), ('CAD', 'Combat à distance'), ('CRA', 'Combat rapproché'), ('SCI', 'Sciences'), ('A&M', 'Arts & Métiers')], default='N/A', max_length=3),
        ),
        migrations.AlterField(
            model_name='coc7skillref',
            name='era',
            field=models.CharField(default=1920, max_length=4),
        ),
        migrations.AlterField(
            model_name='coc7skillref',
            name='smart_code',
            field=models.CharField(default='TBD', max_length=200),
        ),
    ]
