# Generated by Django 2.2 on 2022-05-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0110_auto_20220524_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='alliance',
        ),
    ]
