# Generated by Django 2.2 on 2021-01-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0111_auto_20210102_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigator',
            options={'verbose_name': 'COC7: Investigator'},
        ),
    ]
