# Generated by Django 2.2 on 2022-05-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0111_remove_character_alliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alliance',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
