# Generated by Django 2.2 on 2022-05-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0113_remove_character_alliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience_details',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
