# Generated by Django 2.2 on 2021-01-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0113_coc7occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coc7occupation',
            name='credit_max',
            field=models.PositiveIntegerField(default='99'),
        ),
        migrations.AddField(
            model_name='coc7occupation',
            name='credit_min',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
