# Generated by Django 2.2 on 2022-05-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0114_character_experience_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='core',
            field=models.BooleanField(default=True),
        ),
    ]
