# Generated by Django 2.2 on 2021-01-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0114_auto_20210103_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='coc7skillref',
            name='special_base',
            field=models.CharField(choices=[('N/A', 'NORMAL'), ('DEX based', 'DEX/2'), ('EDU based', 'EDU')], default='N/A', max_length=16),
        ),
    ]
