# Generated by Django 2.2 on 2021-01-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0115_coc7skillref_special_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coc7skillref',
            name='category',
            field=models.CharField(choices=[('N/A', 'Aucune'), ('CAD', 'Combat à distance'), ('CRA', 'Combat rapproché'), ('SCI', 'Sciences'), ('A&M', 'Arts & Métiers'), ('SOC', 'Social')], default='N/A', max_length=3),
        ),
    ]
