# Generated by Django 2.2 on 2022-05-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0115_tourofdutyref_core'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyberware',
            options={'verbose_name': 'FICS: Cyberware'},
        ),
        migrations.AlterModelOptions(
            name='cyberwareref',
            options={'verbose_name': 'FICS: Cyberware Ref'},
        ),
    ]
