# Generated by Django 2.2 on 2022-05-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0116_auto_20220526_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coc7skill',
            name='investigator',
        ),
        migrations.RemoveField(
            model_name='coc7skill',
            name='skill_ref',
        ),
        migrations.RemoveField(
            model_name='coc7skillmodificator',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='coc7skillmodificator',
            name='skill_ref',
        ),
        migrations.RemoveField(
            model_name='coc7skillref',
            name='linked_to',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='occupation',
        ),
        migrations.DeleteModel(
            name='Coc7Occupation',
        ),
        migrations.DeleteModel(
            name='Coc7Skill',
        ),
        migrations.DeleteModel(
            name='Coc7SkillModificator',
        ),
        migrations.DeleteModel(
            name='Coc7SkillRef',
        ),
        migrations.DeleteModel(
            name='Investigator',
        ),
    ]
