# Generated by Django 2.2 on 2022-08-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0117_auto_20220526_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='new_narrative',
            field=models.BooleanField(default=False),
        ),
    ]
