# Generated by Django 2.2 on 2021-01-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0117_auto_20210103_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coc7SkillModificator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Coc7Occupation')),
                ('skill_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Coc7SkillRef')),
            ],
            options={
                'ordering': ['skill_ref'],
            },
        ),
    ]
