# Generated by Django 2.2 on 2022-08-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0118_campaign_new_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='irl_year_start',
            field=models.PositiveIntegerField(blank=True, default=1990),
        ),
    ]
