# Generated by Django 2.2 on 2021-02-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0119_investigator_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorref',
            name='category',
            field=models.CharField(choices=[('Soft', 'Soft Armor'), ('Medium', 'Medium Armor'), ('Hard', 'Hard Armor')], default='Soft', max_length=6),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='cost',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='description',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='encumbrance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='reference',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='stopping_power',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='tech_level',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='beneficeaffliction',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='beneficeafflictioncusto',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='beneficeafflictionmodificator',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='beneficeafflictionref',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='beneficeafflictionref',
            name='emphasis',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='beneficeafflictionref',
            name='source',
            field=models.CharField(default='FS2CRB', max_length=32),
        ),
        migrations.AlterField(
            model_name='beneficeafflictionref',
            name='watermark',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='blessingcurseref',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='blessingcurseref',
            name='source',
            field=models.CharField(default='FS2CRB', max_length=32),
        ),
        migrations.AlterField(
            model_name='bloke',
            name='description',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='smart_code',
            field=models.CharField(default='xxxxxx', max_length=6),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(default='aaa', max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='alias',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='alliance',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='alliance_hash',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='alliance_picture',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='character',
            name='build_log',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='caste',
            field=models.CharField(default='Freefolk', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='challenge',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='color',
            field=models.CharField(default='#CCCCCC', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='faction',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='gm_shortcuts_pdf',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='native_fief',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='occult',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.CharField(default='https://drive.google.com/open?id=15hdubdMt1t_deSXkbg9dsAjWi5tZwMU0', max_length=1024),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='character',
            name='rank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='stories',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='character',
            name='todo_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='charactercusto',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='charactercusto',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='charactercusto',
            name='watch_roots',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gear',
            name='description',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='loot',
            name='code',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='loot',
            name='description',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='loot',
            name='group',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='loot',
            name='secret',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='ritualref',
            name='description',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='ritualref',
            name='drawbacks',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='ritualref',
            name='duration',
            field=models.CharField(choices=[('0', 'Instant'), ('1', 'Temporary'), ('2', 'Prolonged'), ('2', 'Perpetual')], default='ins', max_length=32),
        ),
        migrations.AlterField(
            model_name='ritualref',
            name='modus_operandi',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='ritualref',
            name='path',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='ritualref',
            name='range',
            field=models.CharField(choices=[('0', 'Touch'), ('1', 'Sight'), ('2', 'Sensory'), ('3', 'Distance')], default='tou', max_length=32),
        ),
        migrations.AlterField(
            model_name='specie',
            name='description',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='specie',
            name='race',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='specie',
            name='species',
            field=models.CharField(default=1, max_length=64),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='caste',
            field=models.CharField(choices=[('Nobility', 'Nobility'), ('Church', 'Church'), ('Guild', 'Guild'), ('Alien', 'Alien'), ('Other', 'Other'), ('Freefolk', 'Freefolk')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='category',
            field=models.CharField(choices=[('0', 'Birthright'), ('5', 'Balance'), ('10', 'Upbringing'), ('20', 'Apprenticeship'), ('30', 'Early Career'), ('40', 'Tour of Duty'), ('50', 'Worldly Benefits'), ('60', 'Nameless Kit')], default='Tour of Duty', max_length=20),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='reference',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='source',
            field=models.CharField(default='FS2CRB', max_length=32),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='topic',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='ammoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='availability',
            field=models.CharField(choices=[('E', 'Excellent'), ('C', 'Common'), ('P', 'Poor'), ('R', 'Rare')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='caliber',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='category',
            field=models.CharField(choices=[('MELEE', 'Melee weapon'), ('P', 'Pistol/revolver'), ('RIF', 'Rifle'), ('SMG', 'Submachinegun'), ('SHG', 'Shotgun'), ('HVY', 'Heavy weapon'), ('EX', 'Exotic weapon'), ('SP', 'Special')], default='RIF', max_length=5),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='clip',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='conceilable',
            field=models.CharField(choices=[('P', 'Pocket'), ('J', 'Jacket'), ('L', 'Long coat'), ('N', "Can't be hidden")], default='J', max_length=1),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='damage_class',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='description',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='meta_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='origins',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='reference',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='rel',
            field=models.CharField(choices=[('VR', 'Very reliable'), ('ST', 'Standard'), ('UR', 'Unreliable')], default='ST', max_length=2),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='rng',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='rof',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='stats',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='str_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='tech_level',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='weaponref',
            name='weapon_accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
