# Generated by Django 2.2 on 2022-09-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0120_auto_20220905_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipref',
            name='cs_battle_shields',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_bulk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_cargo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_crew',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_engine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_fusion_core',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_guns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_sensors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_think_machine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_thrust',
            field=models.IntegerField(default=0),
        ),
    ]
