# Generated by Django 2.2 on 2021-02-11 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0120_auto_20210211_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipsection',
            name='ship_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.ShipRef'),
        ),
    ]
