# Generated by Django 2.2 on 2021-02-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0121_auto_20210211_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=128)),
                ('category', models.CharField(choices=[('nobility', 'Nobility'), ('church', 'Church'), ('guild', 'Guild')], default='guild', max_length=10)),
                ('color_front', models.CharField(default='888888', max_length=6)),
                ('color_back', models.CharField(default='888888', max_length=6)),
            ],
            options={
                'verbose_name': 'FICS: Alliance',
                'ordering': ['reference', 'category'],
            },
        ),
    ]
