# Generated by Django 2.2 on 2022-09-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0121_auto_20220913_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipref',
            name='cs_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_autonomy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_maneuver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_scan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_soak',
            field=models.IntegerField(default=0),
        ),
    ]
