# Generated by Django 5.0.6 on 2024-09-12 01:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0122_auto_20220913_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allianceref',
            name='color_back',
            field=colorfield.fields.ColorField(default='#666666', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='allianceref',
            name='color_front',
            field=colorfield.fields.ColorField(default='#AAAAAA', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='allianceref',
            name='color_highlight',
            field=colorfield.fields.ColorField(default='#111111', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='allianceref',
            name='color_icon_fill',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='allianceref',
            name='color_icon_stroke',
            field=colorfield.fields.ColorField(default='#888888', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#CCCCCC', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='group_color',
            field=colorfield.fields.ColorField(blank=True, default='#888888', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='shipsection',
            name='links',
            field=models.ManyToManyField(blank=True, to='collector.shipsection'),
        ),
    ]
