# Generated by Django 2.2 on 2021-02-12 00:25

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0122_allianceref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allianceref',
            name='category',
            field=models.CharField(choices=[('nobility', 'Nobility'), ('church', 'Church'), ('guild', 'Guild'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='allianceref',
            name='color_back',
            field=colorfield.fields.ColorField(default='#666666', max_length=18),
        ),
        migrations.AlterField(
            model_name='allianceref',
            name='color_front',
            field=colorfield.fields.ColorField(default='#AAAAAA', max_length=18),
        ),
    ]
