# Generated by Django 3.2 on 2022-11-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0122_auto_20220913_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
