# Generated by Django 2.2 on 2021-02-13 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0123_auto_20210212_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alliance_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.AllianceRef'),
        ),
    ]
