# Generated by Django 4.1.4 on 2023-01-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0123_alter_shipref_options_alter_shipsystem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='AP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='OCC_DRK',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='OCC_LVL',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='OP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='age_offset',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='challenge_value',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience_balance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='native_fief',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='shield_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp_earned',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp_pool',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp_spent',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
