# Generated by Django 4.1.4 on 2023-01-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0124_alter_character_ap_alter_character_occ_drk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='birthdate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='caste',
            field=models.CharField(blank=True, default='Freefolk', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, default='female', max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.IntegerField(blank=True, default=150),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.IntegerField(blank=True, default=50),
        ),
    ]
