# Generated by Django 5.0 on 2024-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0124_alter_allianceref_id_alter_armor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillref',
            name='uuid',
        ),
        migrations.AddField(
            model_name='allianceref',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='skill',
            name='character_rid',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='skill',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_ref_rid',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='skillref',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='skillref',
            name='group',
            field=models.CharField(blank=True, choices=[('AWA', 'Awareness'), ('BOD', 'Physical'), ('CON', 'Control'), ('DIP', 'Diplomacy'), ('EDU', 'Education'), ('FIG', 'Combat'), ('PER', 'Performance'), ('SOC', 'Social'), ('SPI', 'Spirituality'), ('TIN', 'Tinkering'), ('UND', 'Underworld')], default='EDU', max_length=3),
        ),
        migrations.AlterField(
            model_name='skillref',
            name='is_common',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='skillref',
            name='is_root',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='skillref',
            name='is_speciality',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='skillref',
            name='is_wildcard',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='skillref',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
