# Generated by Django 3.2 on 2022-11-03 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0124_auto_20221103_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 17, 46, 58, 792219, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
