# Generated by Django 2.2 on 2021-02-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0125_auto_20210214_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='build_log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
