# Generated by Django 3.2 on 2022-11-03 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0125_alter_tourofdutyref_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
    ]
