# Generated by Django 5.0 on 2024-10-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0125_remove_skillref_uuid_allianceref_rid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alliance_rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='current_fielf_rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='fief_rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='specie_rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='specie',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
