# Generated by Django 5.0 on 2024-10-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0126_character_alliance_rid_character_current_fielf_rid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='subrace',
            field=models.CharField(default='', max_length=64),
        ),
    ]
