# Generated by Django 2.2 on 2021-02-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0126_auto_20210214_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficeafflictionref',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='beneficeafflictionref',
            name='emphasis',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='beneficeafflictionref',
            name='watermark',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='alliance_picture',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='character',
            name='occult',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='todo_list',
            field=models.TextField(blank=True, default=''),
        ),
    ]
