# Generated by Django 3.2 on 2022-11-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0126_alter_tourofdutyref_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyberwareref',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='tourofdutyref',
            name='pub_date',
        ),
    ]
