# Generated by Django 5.0 on 2024-10-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0127_specie_subrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='race',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='specie',
            name='subrace',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
