# Generated by Django 3.2 on 2022-11-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0127_auto_20221103_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsystem',
            name='free_category',
            field=models.CharField(blank=True, default='n/a', max_length=64),
        ),
        migrations.AddField(
            model_name='shipsystem',
            name='is_symetric',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipsystem',
            name='performance',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shipsystem',
            name='tech_level',
            field=models.IntegerField(default=6),
        ),
    ]
