# Generated by Django 2.2 on 2021-02-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0127_auto_20210214_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficeaffliction',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
