# Generated by Django 4.1.4 on 2023-03-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0127_alter_campaign_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('census', models.PositiveIntegerField(blank=True, default=0)),
                ('members', models.ManyToManyField(to='collector.character')),
            ],
            options={
                'verbose_name': 'FICS: Collection',
                'ordering': ['reference'],
            },
        ),
    ]
