# Generated by Django 2.2 on 2021-02-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0128_auto_20210214_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gm_shortcuts_pdf',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='stories',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
