# Generated by Django 3.2 on 2022-11-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0128_auto_20221103_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsystem',
            name='slot_consumption',
            field=models.IntegerField(default=1),
        ),
    ]
