# Generated by Django 4.1.4 on 2023-03-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0128_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='category',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='collection',
            name='members',
            field=models.ManyToManyField(blank=True, to='collector.character'),
        ),
    ]
