# Generated by Django 5.0 on 2024-10-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0128_alter_specie_race_alter_specie_subrace'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(blank=True, default='', max_length=128)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('group', models.CharField(blank=True, choices=[('GENE', 'Generic'), ('SECT', 'Sects'), ('FOLO', 'Forbidden Lore'), ('HOUS', 'Houses'), ('GUIL', 'Guilds'), ('POTM', 'Privilege Of The Martyrs'), ('DOGM', 'Dogma'), ('SYST', 'Systems'), ('SPEC', 'Species'), ('HOLD', 'Householding'), ('UNDR', 'Underworld')], default='GENE', max_length=4)),
                ('deprecated', models.BooleanField(blank=True, default=False)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
            ],
            options={
                'verbose_name': 'FICS: Degree',
                'ordering': ['reference', 'group'],
            },
        ),
    ]
