# Generated by Django 2.2 on 2021-02-15 10:02

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0129_auto_20210214_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceref',
            name='color_highlight',
            field=colorfield.fields.ColorField(default='#111111', max_length=18),
        ),
        migrations.AddField(
            model_name='allianceref',
            name='faction',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
