# Generated by Django 3.2 on 2022-11-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartograph', '0006_system_description'),
        ('collector', '0129_shipsystem_slot_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceship',
            name='registration_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartograph.system'),
        ),
    ]
