# Generated by Django 5.0 on 2024-10-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0129_degreeref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillref',
            options={'ordering': ['group', 'reference'], 'verbose_name': 'FICS: Skill'},
        ),
        migrations.AlterField(
            model_name='allianceref',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='degreeref',
            name='group',
            field=models.CharField(blank=True, choices=[('GENE', 'Generic'), ('SECT', 'Sects'), ('FOLO', 'Forbidden Lore'), ('HOUS', 'Houses'), ('GUIL', 'Guilds'), ('POTM', 'Privilege Of The Martyrs'), ('DOGM', 'Dogma'), ('SYST', 'Systems'), ('SPEC', 'Species'), ('HOLD', 'Householding'), ('UNDR', 'Underworld'), ('MACA', 'Magna Carta')], default='GENE', max_length=4),
        ),
        migrations.AlterField(
            model_name='degreeref',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='character_rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_ref_rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='skillref',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='specie',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
