# Generated by Django 4.1.4 on 2023-03-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0129_collection_category_alter_collection_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='balanced_ratio',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
