# Generated by Django 4.1.4 on 2023-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0130_collection_balanced_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
