# Generated by Django 3.2 on 2022-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0130_spaceship_registration_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceship',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
