# Generated by Django 5.0 on 2024-10-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0130_alter_skillref_options_alter_allianceref_rid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blessingcurseref',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
