# Generated by Django 2.2 on 2021-02-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0130_auto_20210215_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceref',
            name='icon_complex',
            field=models.CharField(blank=True, default='', max_length=258),
        ),
        migrations.AddField(
            model_name='allianceref',
            name='icon_simple',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
