# Generated by Django 2.2 on 2021-02-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0131_auto_20210215_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.CharField(blank=True, default='https://drive.google.com/open?id=15hdubdMt1t_deSXkbg9dsAjWi5tZwMU0', max_length=1024),
        ),
    ]
