# Generated by Django 4.1.4 on 2023-03-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0131_character_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='incompatibility',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
