# Generated by Django 5.0 on 2024-10-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0131_blessingcurseref_rid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='PA_REF',
            new_name='PA_DEX',
        ),
        migrations.RenameField(
            model_name='charactercusto',
            old_name='PA_REF',
            new_name='PA_DEX',
        ),
        migrations.RenameField(
            model_name='tourofdutyref',
            old_name='PA_REF',
            new_name='PA_DEX',
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
