# Generated by Django 3.2 on 2022-11-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0132_alter_shipref_ship_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipsystemslot',
            name='shipsection',
        ),
        migrations.AddField(
            model_name='shipsystemslot',
            name='shipref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.shipref'),
        ),
        migrations.DeleteModel(
            name='ShipSection',
        ),
    ]
