# Generated by Django 5.0 on 2024-10-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0132_rename_pa_ref_character_pa_dex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillref',
            name='group',
            field=models.CharField(blank=True, choices=[('AWA', 'Awareness'), ('BOD', 'Physical'), ('CON', 'Control'), ('DIP', 'Diplomacy'), ('EDU', 'Education'), ('FIG', 'Combat'), ('PER', 'Performance'), ('SOC', 'Social'), ('SPI', 'Spirituality'), ('TIN', 'Tinkering'), ('UND', 'Underworld'), ('ITO', 'Introspection'), ('ITE', 'Interaction')], default='EDU', max_length=3),
        ),
    ]
