# Generated by Django 2.2 on 2021-02-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0132_auto_20210215_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allianceref',
            name='category',
            field=models.CharField(choices=[('nobility', 'Royale Nobility'), ('minor_nobility', 'Nobility'), ('church', 'Church'), ('minor_sects', 'Minor Sects of the Church'), ('guild', 'Guild'), ('minor_guild', 'Minor Guilds'), ('outlaw', 'Terrorist Groups'), ('foes', 'Enemies of the Crown'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
