# Generated by Django 4.1.4 on 2023-04-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0132_character_incompatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
