# Generated by Django 4.1.4 on 2023-04-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0133_character_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercusto',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='charactercusto',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='charactercusto',
            name='watch_roots',
            field=models.TextField(blank=True, default=''),
        ),
    ]
