# Generated by Django 5.0 on 2024-10-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0133_alter_skillref_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcusto',
            options={'ordering': ['character_custo']},
        ),
        migrations.RemoveField(
            model_name='skillref',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='skillref',
            name='grouping',
        ),
        migrations.RemoveField(
            model_name='skillref',
            name='is_root',
        ),
        migrations.RemoveField(
            model_name='skillref',
            name='is_speciality',
        ),
        migrations.RemoveField(
            model_name='skillref',
            name='is_wildcard',
        ),
        migrations.RemoveField(
            model_name='skillref',
            name='linked_to',
        ),
    ]
