# Generated by Django 2.2 on 2021-02-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0134_auto_20210215_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='color',
            field=models.CharField(blank=True, default='#CCCCCC', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
