# Generated by Django 3.2 on 2022-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0134_shipref_structure_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsystem',
            name='affects',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shipsystemslot',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
