# Generated by Django 4.1.4 on 2023-04-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0134_alter_charactercusto_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
