# Generated by Django 5.0 on 2024-11-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0134_alter_skillcusto_options_remove_skillref_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillref',
            name='acro',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
