# Generated by Django 4.1.4 on 2023-04-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0135_collection_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='classification',
            field=models.CharField(blank=True, choices=[('int', 'Intimate'), ('std', 'Standard'), ('sec', 'Secret'), ('ves', 'Very Secret')], default='std', max_length=3),
        ),
        migrations.AddField(
            model_name='character',
            name='incognito_alliance',
            field=models.CharField(blank=True, default='Unknown Faction', max_length=128),
        ),
        migrations.AddField(
            model_name='character',
            name='incognito_name',
            field=models.CharField(blank=True, default='Unkown Agent', max_length=128),
        ),
    ]
