# Generated by Django 3.2 on 2022-11-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0135_auto_20221104_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipsystem',
            old_name='affects',
            new_name='strategical_effects',
        ),
        migrations.AddField(
            model_name='shipsystem',
            name='tactical_effects',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
