# Generated by Django 5.0 on 2024-11-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0135_skillref_acro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='degree_modificators_summary',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='skill_modificators_summary',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.CreateModel(
            name='DegreeModificator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('degree_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.degreeref')),
                ('tour_of_duty_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.tourofdutyref')),
            ],
            options={
                'ordering': ['degree_ref'],
            },
        ),
    ]
