# Generated by Django 2.2 on 2021-02-16 01:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0135_auto_20210215_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceref',
            name='color_icon_fill',
            field=colorfield.fields.ColorField(default='#333333', max_length=18),
        ),
        migrations.AddField(
            model_name='allianceref',
            name='color_icon_stroke',
            field=colorfield.fields.ColorField(default='#888888', max_length=18),
        ),
    ]
