# Generated by Django 5.0 on 2024-11-16 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0136_tourofdutyref_degree_modificators_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('character_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.charactercusto')),
                ('degree_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.degreeref')),
            ],
            options={
                'ordering': ['character_custo'],
            },
        ),
    ]
