# Generated by Django 2.2 on 2021-02-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0136_auto_20210216_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
