# Generated by Django 4.1.4 on 2023-04-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0136_character_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='reference',
            field=models.CharField(blank=True, choices=[('FS2CRB', 'Fading Suns 2ed Core Rulebook'), ('DEM', 'Introduced in epic Deus Ex Machina'), ('ANTU', 'Introduced in epic Abusus Non Tollit Usum'), ('DAL', 'Introduced in epic De Automatum Legis'), ('MotJ', 'Merchants of the Jumpweb'), ('FL:T', 'Forbidden Lore: Technology'), ('AT', 'Arcane Tech'), ('FSC', 'Fading Suns Companion')], default='MotJ', max_length=32, null=True),
        ),
    ]
