# Generated by Django 3.2 on 2022-11-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0136_auto_20221104_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipsystem',
            name='strategical_effects',
            field=models.CharField(blank=True, default='n/a', max_length=64),
        ),
        migrations.AlterField(
            model_name='shipsystem',
            name='tactical_effects',
            field=models.CharField(blank=True, default='n/a', max_length=64),
        ),
    ]
