# Generated by Django 4.1.4 on 2023-04-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0137_alter_gear_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_core',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
