# Generated by Django 5.0 on 2024-11-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0137_degreecusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='BAP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='BCP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='DP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='SP',
            field=models.IntegerField(default=0),
        ),
    ]
