# Generated by Django 3.2 on 2022-11-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0137_auto_20221104_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsystem',
            name='power_consumption',
            field=models.IntegerField(default=30),
        ),
    ]
