# Generated by Django 2.2 on 2021-02-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0137_auto_20210216_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficeafflictioncusto',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='beneficeafflictionmodificator',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
