# Generated by Django 4.1.4 on 2023-04-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0138_character_is_core'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourofdutyref',
            options={'ordering': ['-core', 'category', 'caste', 'reference'], 'verbose_name': 'FICS: ToD'},
        ),
    ]
