# Generated by Django 5.0 on 2024-11-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0138_tourofdutyref_bap_tourofdutyref_bcp_tourofdutyref_dp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='beneficeaffliction_modificators_summary',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='blessingcurse_modificators_summary',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
