# Generated by Django 3.2 on 2022-11-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0138_shipsystem_power_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsystem',
            name='power_stack',
            field=models.IntegerField(default=0),
        ),
    ]
