# Generated by Django 2.2 on 2021-02-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0138_auto_20210216_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillref',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
