# Generated by Django 4.1.4 on 2023-04-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0139_alter_tourofdutyref_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberfeature',
            name='mods',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
