# Generated by Django 2.2 on 2021-02-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0139_skillref_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillref',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
