# Generated by Django 5.0 on 2024-11-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0139_tourofdutyref_beneficeaffliction_modificators_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourofdutyref',
            old_name='OCC_DRK',
            new_name='PA_DRK',
        ),
        migrations.RenameField(
            model_name='tourofdutyref',
            old_name='OCC_LVL',
            new_name='PA_OCC',
        ),
    ]
