# Generated by Django 3.2 on 2022-11-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0139_shipsystem_power_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipsystem',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='shipsystem',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='shipsystem',
            name='firebirds',
        ),
        migrations.RemoveField(
            model_name='shipsystem',
            name='firebirds_per_rating',
        ),
        migrations.RemoveField(
            model_name='shipsystem',
            name='pts',
        ),
        migrations.RemoveField(
            model_name='shipsystem',
            name='pts_per_rating',
        ),
        migrations.RemoveField(
            model_name='shipsystem',
            name='shield_effects',
        ),
        migrations.RemoveField(
            model_name='shipsystem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='shipsystem',
            name='slot_consumption',
        ),
        migrations.AddField(
            model_name='shipsystem',
            name='type',
            field=models.CharField(default='n/a', max_length=64),
        ),
        migrations.AlterField(
            model_name='shipsystem',
            name='is_symetric',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipsystem',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shipsystem',
            name='structure_points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
