# Generated by Django 3.2 on 2022-11-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0140_auto_20221104_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipsystem',
            name='type',
            field=models.CharField(default='standard', max_length=64),
        ),
    ]
