# Generated by Django 5.0 on 2024-11-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0140_rename_occ_drk_tourofdutyref_pa_drk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_DRK',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_OCC',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
