# Generated by Django 3.2 on 2022-11-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0141_alter_shipsystem_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipref',
            options={'ordering': ['builder'], 'verbose_name': 'Spacecraft: Ship Reference'},
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='battle_shields',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='bridge_min',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='crew_engineers',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='crew_gunners',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='crew_jetjockeys',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='crew_marauders',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='crew_marines',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='crew_pilots',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='jump_capability',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='ship_engines',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='ship_shields',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='size_rating',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='thrust_speed',
        ),
        migrations.RemoveField(
            model_name='shipsystem',
            name='category',
        ),
        migrations.AlterField(
            model_name='shipref',
            name='ship_grade',
            field=models.CharField(blank=True, choices=[('0', 'Lander'), ('1', 'Atmospheric'), ('2', 'Void')], default='Void', max_length=30),
        ),
    ]
