# Generated by Django 2.2 on 2021-02-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0141_beneficeafflictionref_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='ranking',
            field=models.BooleanField(default=False),
        ),
    ]
