# Generated by Django 5.0 on 2024-11-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0141_alter_tourofdutyref_pa_drk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
