# Generated by Django 2.2 on 2021-02-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0142_beneficeafflictionref_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ranking',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
