# Generated by Django 3.2 on 2022-11-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0142_auto_20221104_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceship',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=512, null=True),
        ),
    ]
