# Generated by Django 3.2 on 2022-11-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0143_alter_spaceship_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipref',
            name='ship_status',
            field=models.CharField(choices=[('wip', 'Work In Progress'), ('combat_ready', 'Combat Ready'), ('req_not_met', 'Minimum Ship Requirements not Met')], default='wip', max_length=30),
        ),
    ]
