# Generated by Django 5.0 on 2024-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0143_skillref_as_wildcard_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillref',
            name='acro',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
