# Generated by Django 2.2 on 2021-02-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0143_character_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
