# Generated by Django 5.0 on 2024-11-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0144_alter_skillref_acro'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeref',
            name='as_wildcard_of',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
