# Generated by Django 3.2 on 2022-11-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0144_alter_shipref_ship_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipsystem',
            options={'verbose_name': 'Spacecraft: Ship System'},
        ),
        migrations.AddField(
            model_name='shipsystem',
            name='is_continuous_usage',
            field=models.BooleanField(default=True),
        ),
    ]
