# Generated by Django 2.2 on 2021-02-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0144_auto_20210220_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='team',
            field=models.CharField(blank=True, choices=[('foe', 'Foe'), ('enemy', 'Enemy'), ('lackey', 'Lackey'), ('antagonist', 'Antagonist'), ('opponent', 'Opponent'), ('neutral', 'Neutral'), ('partisan', 'Partisan'), ('protagonist', 'Protagonist'), ('servant', 'Servant'), ('ally', 'Ally'), ('friend', 'Friend')], default='neutral', max_length=128),
        ),
    ]
