# Generated by Django 3.2 on 2022-11-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0145_auto_20221104_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsystem',
            name='structure_points_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
