# Generated by Django 5.0 on 2024-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0145_degreeref_as_wildcard_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeref',
            name='is_wildcard',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='skillref',
            name='is_wildcard',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
