# Generated by Django 2.2 on 2021-02-22 01:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0145_character_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='group_color',
            field=colorfield.fields.ColorField(blank=True, default='#888888', max_length=18),
        ),
        migrations.AlterField(
            model_name='character',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#CCCCCC', max_length=18),
        ),
    ]
