# Generated by Django 5.0 on 2024-11-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0146_degreeref_is_wildcard_skillref_is_wildcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeref',
            name='level',
            field=models.CharField(blank=True, choices=[('CO', '0 - Common'), ('RE', '1 - Restricted'), ('EL', '2 - Elite'), ('OB', '3 - Obscure'), ('FO', '4 - Forbidden')], default='CO', max_length=2),
        ),
    ]
