# Generated by Django 3.2 on 2022-11-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0146_shipsystem_structure_points_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipsystem',
            name='structure_points_used',
        ),
        migrations.AddField(
            model_name='shipref',
            name='structure_points_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
