# Generated by Django 2.2 on 2021-02-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0146_auto_20210222_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillref',
            name='attributes',
            field=models.TextField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='skillref',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
