# Generated by Django 3.2 on 2022-11-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0147_auto_20221104_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsystem',
            name='deus_irae',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
