# Generated by Django 2.2 on 2021-02-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0147_auto_20210222_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillref',
            name='grouping',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
