# Generated by Django 5.0 on 2024-11-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0147_degreeref_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(blank=True, default='', max_length=200)),
                ('skill_ref_rid', models.CharField(blank=True, default='', max_length=200)),
                ('character_rid', models.CharField(blank=True, default='', max_length=200)),
                ('value', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.character')),
                ('degree_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.degreeref')),
            ],
            options={
                'verbose_name': 'Degree',
                'ordering': ['degree_ref'],
            },
        ),
    ]
