# Generated by Django 2.2 on 2021-02-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0148_skillref_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloke',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
