# Generated by Django 3.2 on 2022-11-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0148_shipsystem_deus_irae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipsystem',
            old_name='is_symetric',
            new_name='is_symetrical',
        ),
        migrations.RenameField(
            model_name='shipsystem',
            old_name='deus_irae',
            new_name='pancreator_irae',
        ),
    ]
