# Generated by Django 5.0 on 2024-11-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0148_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='is_kit',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='valid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
