# Generated by Django 3.2 on 2022-11-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0149_auto_20221105_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipsystem',
            name='power_consumption',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shipsystem',
            name='structure_points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
