# Generated by Django 5.0 on 2024-11-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0149_tourofdutyref_is_kit_alter_tourofdutyref_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeref',
            name='group_wildcard',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
