# Generated by Django 2.2 on 2021-02-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0149_auto_20210223_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='path',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
