# Generated by Django 5.0 on 2024-11-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0150_degreeref_group_wildcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='is_public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
