# Generated by Django 3.2 on 2022-11-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0150_auto_20221105_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceship',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
