# Generated by Django 5.0 on 2024-11-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0151_tourofdutyref_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degreeref',
            options={'ordering': ['group', 'reference'], 'verbose_name': 'FICS: Degree'},
        ),
        migrations.AddField(
            model_name='degreeref',
            name='subgroup',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
