# Generated by Django 5.0 on 2024-12-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0152_alter_degreeref_options_degreeref_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercusto',
            name='watch_roots',
            field=models.TextField(blank=True, default=''),
        ),
    ]
