# Generated by Django 3.2 on 2022-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0152_spaceship_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_cast',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
