# Generated by Django 5.0 on 2024-12-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0153_alter_charactercusto_watch_roots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='degreecusto',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='degreemodificator',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='skillcusto',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='skillmodificator',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
