# Generated by Django 3.2 on 2022-11-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0153_character_is_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipref',
            old_name='cs_scan',
            new_name='cs_scanners',
        ),
    ]
