# Generated by Django 3.2 on 2022-11-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0154_rename_cs_scan_shipref_cs_scanners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipref',
            old_name='cs_attack',
            new_name='cs_firepower',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='cs_guns',
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_deflect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_hull',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_life_support',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_power_consumption',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_shields',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_storage_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipref',
            name='cs_structure',
            field=models.IntegerField(default=0),
        ),
    ]
