# Generated by Django 5.0 on 2024-12-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0154_alter_degree_value_alter_degreecusto_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
