# Generated by Django 5.0 on 2024-12-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0155_alter_skill_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='subtopic',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
