# Generated by Django 3.2 on 2022-11-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0155_auto_20221130_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipref',
            name='cs_power_stack',
            field=models.IntegerField(default=0),
        ),
    ]
