# Generated by Django 5.0 on 2024-12-11 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0156_tourofdutyref_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillref',
            name='linked_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.skillref'),
        ),
    ]
