# Generated by Django 3.2 on 2022-12-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0157_shipref_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipref',
            name='points',
        ),
        migrations.RemoveField(
            model_name='shipref',
            name='pts',
        ),
    ]
