# Generated by Django 5.0 on 2024-12-12 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0157_skillref_linked_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='OCC_DRK',
            new_name='PA_DRK',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='OCC_LVL',
            new_name='PA_OCC',
        ),
    ]
