# Generated by Django 5.0 on 2024-12-12 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0158_rename_occ_drk_character_pa_drk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactercusto',
            old_name='OCC_DRK',
            new_name='PA_DRK',
        ),
        migrations.RenameField(
            model_name='charactercusto',
            old_name='OCC_LVL',
            new_name='PA_OCC',
        ),
    ]
