# Generated by Django 3.2 on 2022-12-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0158_auto_20221201_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipsystem',
            options={'ordering': ['type', 'reference'], 'verbose_name': 'Spacecraft: Ship System'},
        ),
    ]
