# Generated by Django 5.0 on 2024-12-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0159_rename_occ_drk_charactercusto_pa_drk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreeref',
            name='deprecated',
        ),
    ]
