# Generated by Django 3.2 on 2022-12-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0159_alter_shipsystem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipref',
            name='has_jump_capability',
            field=models.BooleanField(default=True),
        ),
    ]
