# Generated by Django 3.2 on 2022-12-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0160_shipref_has_jump_capability'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsystemslot',
            name='power_consumption',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='shipsystemslot',
            name='power_stack',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='shipsystemslot',
            name='structure_points',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
