# Generated by Django 5.0 on 2024-12-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0160_remove_degreeref_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeref',
            name='group',
            field=models.CharField(blank=True, choices=[('GENE', 'Generic'), ('SECT', 'Sects'), ('FOLO', 'Forbidden Lore'), ('HOUS', 'Houses'), ('GUIL', 'Guilds'), ('POTM', 'Privilege Of The Martyrs'), ('DOGM', 'Dogma'), ('SYST', 'Systems'), ('SPEC', 'Species'), ('HOLD', 'Householding'), ('UNDR', 'Underworld'), ('MACA', 'Magna Carta'), ('HUMA', 'Humanities')], default='GENE', max_length=4),
        ),
    ]
