# Generated by Django 5.0 on 2024-12-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0161_alter_degreeref_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillref',
            name='deprecated',
        ),
        migrations.AddField(
            model_name='skillref',
            name='group_wildcard',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
