# Generated by Django 5.0 on 2024-12-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0162_remove_skillref_deprecated_skillref_group_wildcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degreemodificator',
            options={'ordering': ['-degree_ref__is_wildcard', 'degree_ref__group', 'degree_ref__reference']},
        ),
        migrations.AlterModelOptions(
            name='degreeref',
            options={'ordering': ['-is_wildcard', 'group', 'reference'], 'verbose_name': 'FICS: Degree'},
        ),
        migrations.AddField(
            model_name='character',
            name='DE_TOTAL',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='is_custom',
            field=models.BooleanField(default=True),
        ),
    ]
