# Generated by Django 3.2 on 2022-12-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0162_auto_20221201_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipref',
            name='cs_power_peak',
            field=models.IntegerField(default=0),
        ),
    ]
