# Generated by Django 3.2 on 2022-12-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0163_shipref_cs_power_peak'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsystem',
            name='firebirds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
