# Generated by Django 5.0 on 2024-12-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0163_alter_degreemodificator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='AP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='BA_TOTAL',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='BC_TOTAL',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='DE_TOTAL',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='OP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_AGI',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_AWA',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_BOD',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_CON',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_DEX',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_DRK',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_INT',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_MOV',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_OCC',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_PRE',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_STR',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_TEC',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_TEM',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_TOTAL',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='PA_WIL',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_DMG',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_END',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_HUM',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_PAS',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_REC',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_RES',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_RUN',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_SPD',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_STA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_STU',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_TOL',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SA_WYR',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='SK_TOTAL',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='TA_TOTAL',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='balanced',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='challenge_value',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='error',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience_balance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='historical_figure',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='life_path_total',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='nameless',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='overhead',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='shield_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='stories_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp_earned',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp_pool',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='xp_spent',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
