# Generated by Django 3.2 on 2022-12-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0164_shipsystem_firebirds'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipsystemslot',
            name='firebirds',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
