# Generated by Django 5.0 on 2024-12-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0164_alter_character_ap_alter_character_ba_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='DWP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='SWP',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
