# Generated by Django 5.0 on 2024-12-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0165_tourofdutyref_dwp_tourofdutyref_swp'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercusto',
            name='degree_wp_watch',
            field=models.TextField(blank=True, default=''),
        ),
    ]
