# Generated by Django 3.2 on 2022-12-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0165_shipsystemslot_firebirds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipref',
            name='ship_class',
            field=models.CharField(blank=True, choices=[('0', 'Fighter'), ('1', 'Shuttle'), ('2', 'Bomber'), ('3', 'Explorer'), ('4', 'Raider'), ('5', 'Escort'), ('6', 'Corvette'), ('7', 'Frigate'), ('8', 'Galliot'), ('9', 'Fast Freighter'), ('10', 'Small Freighter'), ('11', 'Assault Lander'), ('12', 'Destroyer'), ('13', 'Cruiser'), ('14', 'Large Freighter'), ('15', 'Luxury Liner'), ('16', 'Dreadnough'), ('17', 'Carrier'), ('18', 'Space Station'), ('19', 'Atmospheric Transporter'), ('20', 'Jumptug')], default='Shuttle', max_length=30),
        ),
    ]
