# Generated by Django 5.0 on 2024-12-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0166_charactercusto_degree_wp_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactercusto',
            name='degree_wp_watch',
        ),
    ]
