# Generated by Django 3.2 on 2022-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0166_alter_shipref_ship_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipref',
            name='size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
