# Generated by Django 5.0 on 2024-12-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0167_remove_charactercusto_degree_wp_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='degrees_wp_choices',
            field=models.TextField(blank=True, default='{}', max_length=2048),
        ),
    ]
