# Generated by Django 5.0 on 2025-01-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0168_tourofdutyref_degrees_wp_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degreecusto',
            options={'ordering': ['degree_ref__group', 'degree_ref']},
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='degrees_wp_choices_str',
            field=models.TextField(blank=True, default='{}', max_length=2048),
        ),
    ]
