# Generated by Django 3.2 on 2022-12-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0169_rename_size_shipref_size_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
