# Generated by Django 5.0 on 2025-01-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0169_alter_degreecusto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberwareref',
            name='cost',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
