# Generated by Django 3.2 on 2022-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0170_character_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='use_only_entrance',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
