# Generated by Django 5.0 on 2025-01-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0170_cyberwareref_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberware',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
