# Generated by Django 5.0 on 2025-01-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0171_cyberware_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberwareref',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
