# Generated by Django 5.0 on 2025-01-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0172_cyberwareref_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='incomp',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
