# Generated by Django 5.0 on 2025-01-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0173_character_incomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sanity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
