# Generated by Django 3.2 on 2022-12-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0173_character_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='entrance',
            field=models.TextField(blank=True, default=''),
        ),
    ]
