# Generated by Django 5.0 on 2025-01-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0174_character_sanity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorref',
            name='cost',
            field=models.PositiveIntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='armorref',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
