# Generated by Django 5.0 on 2025-01-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0175_alter_armorref_cost_alter_armorref_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armorref',
            old_name='left_arm',
            new_name='weak_arm',
        ),
    ]
