# Generated by Django 5.0 on 2025-01-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0176_rename_left_arm_armorref_weak_arm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armorref',
            old_name='right_arm',
            new_name='strong_arm',
        ),
    ]
