# Generated by Django 5.0 on 2025-01-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0177_rename_right_arm_armorref_strong_arm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armorref',
            old_name='right_leg',
            new_name='strong_leg',
        ),
        migrations.RenameField(
            model_name='armorref',
            old_name='left_leg',
            new_name='weak_leg',
        ),
    ]
