# Generated by Django 5.0 on 2025-01-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0178_rename_right_leg_armorref_strong_leg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armorref',
            name='cost',
        ),
    ]
