# Generated by Django 5.0 on 2025-01-18 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0179_remove_armorref_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourofdutyref',
            old_name='BAP',
            new_name='BA',
        ),
        migrations.RenameField(
            model_name='tourofdutyref',
            old_name='BCP',
            new_name='BC',
        ),
        migrations.RenameField(
            model_name='tourofdutyref',
            old_name='DP',
            new_name='DE',
        ),
        migrations.RenameField(
            model_name='tourofdutyref',
            old_name='SP',
            new_name='SK',
        ),
    ]
