# Generated by Django 5.0 on 2025-02-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0180_rename_bap_tourofdutyref_ba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipref',
            name='model_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
