# Generated by Django 5.0 on 2025-02-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0181_shipref_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceship',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
