# Generated by Django 5.0 on 2025-03-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0182_spaceship_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='shortcut',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='blessingcurseref',
            name='shortcut',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
    ]
