# Generated by Django 5.0 on 2025-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0183_beneficeafflictionref_shortcut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeaffliction',
            name='shortcut',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
    ]
