# Generated by Django 5.0 on 2025-03-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0184_beneficeaffliction_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blessingcurseref',
            name='shortcut',
            field=models.TextField(blank=True, default='', max_length=64),
        ),
    ]
