# Generated by Django 5.0 on 2025-03-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0185_alter_blessingcurseref_shortcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceref',
            name='internal_index',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='blessingcurseref',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
