# Generated by Django 5.0 on 2025-03-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0186_allianceref_internal_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='indexed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
