# Generated by Django 5.0 on 2025-04-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0187_beneficeafflictionref_indexed'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='blessingcurseref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='character',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='degree',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='degreeref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='skill',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='skillref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='spaceship',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='specie',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
