# Generated by Django 5.0 on 2025-04-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0188_allianceref_cypher_rid_blessingcurseref_cypher_rid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allianceref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blessingcurseref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='degree',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='degreeref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='skillref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='spaceship',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='specie',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
