# Generated by Django 5.0 on 2025-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0189_alter_allianceref_cypher_rid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loot',
            name='code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='loot',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='loot',
            name='group',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='loot',
            name='index',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='loot',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='loot',
            name='secret',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='loot',
            name='session',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='loot',
            name='sleeves_auction',
            field=models.PositiveIntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='loot',
            name='sleeves_authenticity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='loot',
            name='sleeves_fame',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='loot',
            name='sleeves_gossip',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='loot',
            name='sleeves_minimum_increment',
            field=models.PositiveIntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='shipref',
            name='reference',
            field=models.CharField(max_length=64),
        ),
    ]
