# Generated by Django 5.0 on 2025-04-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0190_alter_loot_code_alter_loot_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipref',
            name='builder',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
