# Generated by Django 5.0 on 2025-05-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0191_alter_shipref_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bookmark_tag',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
