# Generated by Django 5.0 on 2025-05-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0192_character_bookmark_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lifepath_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
