# Generated by Django 5.0 on 2025-05-12 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0193_character_lifepath_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='birthdate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='caste',
            field=models.CharField(blank=True, default='Freefolk', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, default='female', max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.IntegerField(blank=True, default=150),
        ),
        migrations.AlterField(
            model_name='character',
            name='importance',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='native_fief',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.IntegerField(blank=True, default=50),
        ),
    ]
