# Generated by Django 5.0 on 2025-05-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0194_alter_character_age_alter_character_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeref',
            name='level',
            field=models.CharField(blank=True, choices=[('CO', '(I)'), ('RE', '(II)'), ('EL', '(III)'), ('OB', '(IV)'), ('FO', '(V)')], default='CO', max_length=2),
        ),
    ]
