# Generated by Django 5.0 on 2025-06-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0195_alter_degreeref_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='development_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
