# Generated by Django 5.0 on 2025-06-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0196_character_development_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='skills_wp_choices',
            field=models.TextField(blank=True, default='{}', max_length=2048),
        ),
    ]
