# Generated by Django 5.0 on 2025-06-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0197_tourofdutyref_skills_wp_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='refval',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
    ]
