# Generated by Django 5.0 on 2025-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0198_beneficeafflictionref_refval'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeref',
            name='refval',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
