# Generated by Django 5.0 on 2025-06-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0199_degreeref_refval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeref',
            name='level',
            field=models.CharField(blank=True, choices=[('CO', '(1)'), ('RE', '(2)'), ('EL', '(3)'), ('OB', '(4)'), ('FO', '(5)')], default='CO', max_length=2),
        ),
    ]
