# Generated by Django 5.0 on 2025-06-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0200_alter_degreeref_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercusto',
            name='attributes_to_allocate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='degrees_to_allocate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='skills_to_allocate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
