# Generated by Django 5.0 on 2025-06-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0201_charactercusto_attributes_to_allocate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercusto',
            name='allocated_attributes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='allocated_degrees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='allocated_skills',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
