# Generated by Django 5.0 on 2025-06-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0202_charactercusto_allocated_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='attributes_to_allocate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='degrees_to_allocate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='skills_to_allocate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
