# Generated by Django 5.0 on 2025-06-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0203_tourofdutyref_attributes_to_allocate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='stored_allocator',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
