# Generated by Django 5.0 on 2025-06-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0204_tourofdutyref_stored_allocator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='AWP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='PA_C1C',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='PA_C1F',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='PA_C1M',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='PA_C1P',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
