# Generated by Django 5.0 on 2025-06-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0205_tourofdutyref_awp_tourofdutyref_pa_c1c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofdutyref',
            name='BAW',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='BCW',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
