# Generated by Django 5.0 on 2025-06-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0206_tourofdutyref_baw_tourofdutyref_bcw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourofdutyref',
            name='attributes_to_allocate',
        ),
        migrations.RemoveField(
            model_name='tourofdutyref',
            name='degrees_to_allocate',
        ),
        migrations.RemoveField(
            model_name='tourofdutyref',
            name='skills_to_allocate',
        ),
    ]
