# Generated by Django 5.0 on 2025-06-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0207_remove_tourofdutyref_attributes_to_allocate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='degrees_wp_choices',
            field=models.TextField(blank=True, default='{}', max_length=3072),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='skills_wp_choices',
            field=models.TextField(blank=True, default='{}', max_length=3072),
        ),
    ]
