# Generated by Django 5.0 on 2025-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0208_alter_tourofdutyref_degrees_wp_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='degrees_wp_choices',
            field=models.TextField(blank=True, default='{}', max_length=4096),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='skills_wp_choices',
            field=models.TextField(blank=True, default='{}', max_length=4096),
        ),
    ]
