# Generated by Django 5.0 on 2025-07-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0209_alter_tourofdutyref_degrees_wp_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactercusto',
            name='allocated_attributes',
        ),
        migrations.RemoveField(
            model_name='charactercusto',
            name='allocated_degrees',
        ),
        migrations.RemoveField(
            model_name='charactercusto',
            name='allocated_skills',
        ),
        migrations.RemoveField(
            model_name='charactercusto',
            name='attributes_to_allocate',
        ),
        migrations.RemoveField(
            model_name='charactercusto',
            name='degrees_to_allocate',
        ),
        migrations.RemoveField(
            model_name='charactercusto',
            name='skills_to_allocate',
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='stored_allocator',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
