# Generated by Django 5.0 on 2025-07-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0210_remove_charactercusto_allocated_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercusto',
            name='BA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='BC',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='DP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='SP',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
