# Generated by Django 5.0 on 2025-07-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0211_charactercusto_ba_charactercusto_bc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercusto',
            name='AP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charactercusto',
            name='OP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charactercusto',
            name='value',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
