# Generated by Django 5.0 on 2025-07-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0212_alter_charactercusto_ap_alter_charactercusto_op_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercusto',
            name='degrees_wp_choices_str',
            field=models.TextField(blank=True, default='{}', max_length=4096),
        ),
        migrations.AlterField(
            model_name='charactercusto',
            name='stored_allocator',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
    ]
