# Generated by Django 5.0 on 2025-07-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0213_alter_charactercusto_degrees_wp_choices_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercusto',
            name='skills_wp_choices_str',
            field=models.TextField(blank=True, default='{}', max_length=4096),
        ),
    ]
