# Generated by Django 5.0 on 2025-07-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0214_charactercusto_skills_wp_choices_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourofdutyref',
            name='AP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='BA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='BC',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='DE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='OP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_AGI',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_AWA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_BOD',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_CON',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_DEX',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_INT',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_MOV',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_PRE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_STR',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_TEC',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_TEM',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='PA_WIL',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='SK',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tourofdutyref',
            name='WP',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
