# Generated by Django 5.0 on 2025-07-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0215_alter_tourofdutyref_ap_alter_tourofdutyref_ba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='as_wildcard_of',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='group_wildcard',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='is_wildcard',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
