# Generated by Django 5.0 on 2025-07-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0216_beneficeafflictionref_as_wildcard_of_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficeafflictionref',
            options={'ordering': ['reference', 'value'], 'verbose_name': 'FICS: Benefice/Affliction', 'verbose_name_plural': 'FICS: Benefices/Afflictions'},
        ),
    ]
