# Generated by Django 5.0 on 2025-07-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0217_alter_beneficeafflictionref_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blessingcurseref',
            options={'ordering': ['reference'], 'verbose_name': 'FICS: Blessing/Curse', 'verbose_name_plural': 'FICS: Blessings/Curses'},
        ),
    ]
