# Generated by Django 5.0 on 2025-07-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0218_alter_blessingcurseref_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficeafflictionref',
            options={'ordering': ['-is_wildcard', '-group_wildcard', 'reference', 'value'], 'verbose_name': 'FICS: Benefice/Affliction', 'verbose_name_plural': 'FICS: Benefices/Afflictions'},
        ),
    ]
