# Generated by Django 5.0 on 2025-07-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0219_alter_beneficeafflictionref_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='is_affliction',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
