# Generated by Django 5.0 on 2025-07-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0220_beneficeafflictionref_is_affliction'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sanity_loss',
            field=models.TextField(blank=True, default='{}', max_length=1024),
        ),
    ]
