# Generated by Django 5.0 on 2025-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0221_character_sanity_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='blessingcurse',
            name='occurences',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='blessingcursecusto',
            name='occurences',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='blessingcursemodificator',
            name='occurences',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='sanity_loss',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
