# Generated by Django 5.0 on 2025-07-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0222_blessingcurse_occurences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeaffliction',
            name='occurences',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='beneficeafflictioncusto',
            name='occurences',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='beneficeafflictionmodificator',
            name='occurences',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
