# Generated by Django 5.0 on 2025-07-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0223_beneficeaffliction_occurences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='occurences',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='blessingcurseref',
            name='occurences',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
