# Generated by Django 5.0 on 2025-07-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0224_beneficeafflictionref_occurences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficeafflictionref',
            name='uuid',
        ),
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='beneficeafflictionref',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ritualref',
            name='cypher_rid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ritualref',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
