# Generated by Django 5.0 on 2025-07-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0225_remove_beneficeafflictionref_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='option_has_main_epic_access',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='option_display_as_list',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='option_display_count',
            field=models.PositiveIntegerField(blank=True, default=10),
        ),
    ]
