# Generated by Django 5.0 on 2025-07-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0226_profile_option_has_main_epic_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blessingcurseref',
            name='as_wildcard_of',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='blessingcurseref',
            name='group_wildcard',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='blessingcurseref',
            name='is_wildcard',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
