# Generated by Django 5.0 on 2025-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0227_blessingcurseref_as_wildcard_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='BA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='BC',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='DP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='SP',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
