# Generated by Django 5.0 on 2025-07-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0228_character_ba_character_bc_character_dp_character_sp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactercusto',
            name='value',
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='AWP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='BAW',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='BCW',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='DWP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='PA_C1C',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='PA_C1F',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='PA_C1M',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='PA_C1P',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='SWP',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
