# Generated by Django 5.0 on 2025-07-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0229_remove_charactercusto_value_charactercusto_awp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercusto',
            name='LP',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
