# Generated by Django 5.0 on 2025-07-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0230_charactercusto_lp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactercusto',
            name='LP',
        ),
    ]
