# Generated by Django 5.0 on 2025-07-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0231_remove_charactercusto_lp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourofdutyref',
            old_name='DE',
            new_name='DP',
        ),
        migrations.RenameField(
            model_name='tourofdutyref',
            old_name='SK',
            new_name='SP',
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='ba_wp_choices_str',
            field=models.TextField(blank=True, default='{}', max_length=4096),
        ),
        migrations.AddField(
            model_name='charactercusto',
            name='bc_wp_choices_str',
            field=models.TextField(blank=True, default='{}', max_length=4096),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='ba_wp_choices',
            field=models.TextField(blank=True, default='{}', max_length=4096),
        ),
        migrations.AddField(
            model_name='tourofdutyref',
            name='bc_wp_choices',
            field=models.TextField(blank=True, default='{}', max_length=4096),
        ),
    ]
