# Generated by Django 5.0 on 2025-07-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0232_rename_de_tourofdutyref_dp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercusto',
            name='need_fix',
            field=models.BooleanField(default=False),
        ),
    ]
