# Generated by Django 5.0 on 2025-07-22 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0233_charactercusto_need_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourofduty',
            options={'ordering': ['character', 'ref']},
        ),
        migrations.RenameField(
            model_name='tourofduty',
            old_name='tour_of_duty_ref',
            new_name='ref',
        ),
    ]
