# Generated by Django 5.0 on 2025-07-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0234_alter_tourofduty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficeafflictioncusto',
            name='fromTOD',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='blessingcursecusto',
            name='fromTOD',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='degreecusto',
            name='fromTOD',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='skillcusto',
            name='fromTOD',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
