# Generated by Django 5.0 on 2025-07-26 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0236_alter_charactercusto_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercusto',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cc', serialize=False, to='collector.character'),
        ),
    ]
