# Generated by Django 5.0 on 2025-07-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0237_alter_charactercusto_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
