# Generated by Django 5.0 on 2025-07-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0238_alter_degree_value_alter_skill_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourofduty',
            name='OP',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
