# Generated by Django 5.0 on 2025-07-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0239_tourofduty_op'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactercusto',
            name='AWP',
        ),
        migrations.RemoveField(
            model_name='charactercusto',
            name='BAW',
        ),
        migrations.RemoveField(
            model_name='charactercusto',
            name='BCW',
        ),
        migrations.RemoveField(
            model_name='charactercusto',
            name='DWP',
        ),
        migrations.RemoveField(
            model_name='charactercusto',
            name='SWP',
        ),
    ]
