# Generated by Django 5.0 on 2025-07-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0240_remove_charactercusto_awp_remove_charactercusto_baw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourofdutyref',
            old_name='WP',
            new_name='LP',
        ),
    ]
