# Generated by Django 5.0 on 2025-07-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0241_rename_wp_tourofdutyref_lp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourofdutyref',
            name='LP',
        ),
    ]
