# Generated by Django 5.0 on 2025-07-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0242_remove_tourofdutyref_lp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreecusto',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skillcusto',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
