# Generated by Django 5.0 on 2025-07-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0243_alter_degreecusto_value_alter_skillcusto_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcusto',
            name='fromTOD',
        ),
    ]
