# Generated by Django 5.0 on 2025-07-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0244_remove_skillcusto_fromtod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['skill_ref'], 'verbose_name': 'Character Skill', 'verbose_name_plural': 'Character Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillcusto',
            options={'ordering': ['character_custo'], 'verbose_name': 'CC Skill'},
        ),
        migrations.AlterModelOptions(
            name='skillmodificator',
            options={'ordering': ['skill_ref'], 'verbose_name': 'TOD Skill'},
        ),
        migrations.AlterModelOptions(
            name='skillref',
            options={'ordering': ['group', 'reference'], 'verbose_name': 'FICS: Skill', 'verbose_name_plural': 'FICS: Skills'},
        ),
    ]
