# Generated by Django 5.0 on 2025-07-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0245_alter_skill_options_alter_skillcusto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreecusto',
            name='fromTOD',
        ),
        migrations.AlterField(
            model_name='degreecusto',
            name='value',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='skillcusto',
            name='value',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
