# Generated by Django 2.2.7 on 2020-02-13 23:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector', '0014_auto_20200207_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Run date')),
                ('type_of_fight', models.CharField(choices=[('F2F', 'Face to face'), ('H2H', 'Hand to hand'), ('MEL', 'MELEE'), ('RNG', 'RANGED'), ('MIX', 'MIXED')], default='F2F', max_length=3)),
                ('tori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tori', to='collector.Character')),
                ('uke', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uke', to='collector.Character')),
            ],
        ),
    ]
