# Generated by Django 2.2.10 on 2021-03-28 21:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_remove_character_alliance_hash'),
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('is_armored', models.BooleanField(blank=True, default=False)),
                ('is_armed', models.BooleanField(blank=True, default=False)),
                ('has_species_lifepath', models.BooleanField(default=False)),
                ('has_standard_lifepath', models.BooleanField(default=False)),
                ('has_tods_lifepath', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(blank=True, default=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date published')),
                ('last_comment', models.TextField(blank=True, default='', max_length=1024)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Character')),
            ],
            options={
                'verbose_name': 'Optimizer: Character Policy',
                'ordering': ['name'],
            },
        ),
    ]
