# Generated by Django 2.2.10 on 2020-05-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0031_beneficeafflictionmodificator_description'),
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Character')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.Team')),
            ],
        ),
    ]
