# Generated by Django 2.2.7 on 2020-02-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_auto_20200207_1735'),
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('attacker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attacker', to='collector.Character')),
                ('defender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defender', to='collector.Character')),
                ('duel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.Duel')),
            ],
        ),
    ]
