# Generated by Django 2.2.10 on 2020-05-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_teammate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='team',
            name='population',
        ),
    ]
