# Generated by Django 2.2.7 on 2020-02-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_combatround'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='tori',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='type_of_fight',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='uke',
        ),
        migrations.DeleteModel(
            name='CombatRound',
        ),
    ]
