# Generated by Django 2.2.10 on 2021-03-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_balanced',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
