# Generated by Django 2.2 on 2020-11-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_auto_20200530_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
