# Generated by Django 2.2.7 on 2020-02-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_auto_20200218_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duel',
        ),
    ]
