# Generated by Django 2.2 on 2021-11-11 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0074_auto_20211111_2207'),
        ('optimizer', '0003_policy_is_balanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.Campaign'),
        ),
    ]
