# Generated by Django 2.2 on 2020-11-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0004_team_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='seat',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
