# Generated by Django 5.0 on 2025-01-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0006_alter_policy_id_alter_team_id_alter_teammate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialShipCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('complement', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('level', models.IntegerField(blank=True, default=1)),
                ('power', models.IntegerField(blank=True, default=1)),
                ('time_units', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
    ]
