# Generated by Django 5.0 on 2025-01-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0007_celestialshipcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialshipcard',
            name='category',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='celestialshipcard',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
