# Generated by Django 5.0 on 2025-01-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0008_alter_celestialshipcard_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialshipcard',
            name='category',
            field=models.CharField(blank=True, choices=[('PIL', 'Pilot'), ('ENG', 'Engineer'), ('BOTH', 'Both')], default='BOTH', max_length=128),
        ),
    ]
